[quote.epigraph, , Ps. 37:23,39]
____
The steps of a good man are ordered by the Lord;
and he delights in his way.
He is his strength in the time of trouble.
____

[#roberts, short="The Life of John Roberts"]
== Memoirs of the Life of John Roberts by His Son Daniel Roberts

I have had it on my mind, for some years past,
to commit to writing some memorable passages,
the chief of which were transacted in my time,
together with some short account of our family.

My grandfather`'s name was John Roberts, alias John Hayward.
He lived at a village called Siddington, within a mile of Cirencester, in Gloucestershire.
I have heard he lived reputably on a little estate of his own, which he occupied.
He married Mary Solliss, sister to Andrew Solliss, Esq.,
who was in the commission of the peace,
and sustained great spoil in the time of the civil
war between king Charles I. and the Parliament.
I have heard that a colonel and his men and horses quartered
themselves upon his land a considerable time together,
turning their horses to the corn and hay mows.

My father and his next neighbour went into the army under Oliver Cromwell,
and continued till they heard Cirencester was taken by the king`'s party;
when they thought proper to return home,
to see how it fared with their parents and relations.

As they were passing by Cirencester,
they were discovered and pursued by two soldiers of the king`'s party,
then in possession of the town.
Seeing themselves pursued, they quitted their horses, and took to their heels;
but by reason of their accoutrements could make little speed.
The soldiers came upon my father first;
and though he begged for leniency they would give him none;
but laid on him with their swords, cutting and slashing his hands and arms,
which he held up to save his head, as the marks upon them did long after testify.
At length it pleased the Almighty to put it into his mind to fall down on his face;
which he did.
Hereupon the soldiers being on horseback, cried to each other,
"`Dismount and cut his throat!`"
But neither of them did; yet continued to strike and prick him about the jaws,
till they thought him dead.
Then they left him and pursued his neighbor, whom they presently overtook and killed.

Soon after they had left my father, it was said in his heart, "`Rise,
and flee for your life;`" which call he obeyed; and starting upon his feet,
his enemies spied him in motion, and pursued him again.
He ran down a steep hill, and through a river which ran at the bottom of it;
though with exceeding difficulty, his boots filling with water,
and his wounds bleeding very much.
They followed him to the top of the hill; but seeing he had got over,
they pursued him no further.

He was at a loss which way to take in this wounded and disconsolate condition,
being surrounded with enemies on every hand.
At length he determined to go to his uncle Solliss`'s;
from which he sent a servant to a widow at Cirencester,
at whose house the chief officers lay, with whom he was acquainted,
desiring her to come to him; which she readily did,
and offered him all the service in her power.
He desired her, as the principal officers lay at her house,
to use her interest with them to give command that none
of the king`'s soldiers might offer him any abuse;
which she effected,
and in good will to her they likewise sent their ablest surgeon to him.
He was a man of great skill, but of a sour disposition; for he told my father,
"`If I had met you in the field, I would have killed you myself; but now,`" said he,
"`I will cure you;`" which he did.

When my father found himself able, he went to his father`'s house,
and found him very ill in bed.
They greeted each other with many tears, and a great intermixture of joy and sorrow.
After some time my father perceived his father to tremble
to such a degree that the bed shook under him.
Upon which my father asked him how it was with him?
He replied, "`I am well; I feel no pain,--it is the mighty power of God that shakes me.`"
After lying still some time, he broke out in a sweet melody of spirit, saying,
"`In the Lord only have I righteousness and strength!
In God I have salvation!`"
I do not remember to have heard he said anything more before his departure.

The civil war continuing, my father found he could not be safe at home,
and therefore he went again,
and continued till near the conclusion of that dreadful eruption;
when he returned again to his sorrowful family at Siddington.
After some time he took as a wife Lydia Tindall, daughter of Thomas Tindall of Slincomb,
near Dursley, a religious family, and one of those under the denomination of Puritans.
Matthew Hale, afterwards lord chief justice of England, was her kinsman,
and drew her marriage settlement.
It pleased God to give them six children, namely: John, Joseph, Lydia, Thomas,
Nathaniel and Daniel.
Joseph and Lydia died young:
Thomas was killed at the age of fourteen by a kick from a mare;
the rest lived to adulthood.

In the year 1665,
it pleased the Lord to send two women Friends out of the north to Cirencester,
who inquiring after such as feared God, were directed to my father,
as the likeliest person to entertain them.
They came to his house and desired a meeting:
he granted it and invited several of his acquaintance to sit with them.
After some time of silence, the Friends spoke a few words, which had a good effect.
After the meeting, my father endeavored to engage them in discourse;
but they said little, and recommended him to Richard Farnsworth,
then a prisoner for the testimony of Truth in Banbury jail, to whom they were going.

Upon this recommendation my father went shortly after to the prison,
in order to converse with Richard.
There he met with the two women who had been at his house.
The jailer was denying them entrance,
and telling them he had an order not to let any of those "`giddy-headed`" people in;
and therefore if they did go in, he would keep them there;
but upon my father`'s desire they were admitted in along with him,
and conducted through several rooms to a dungeon,
where Richard Farnsworth was preaching through a grate to the people in the street.

Soon after they came in, he desisted, and after a little time of silence,
turning to them, he spoke to this purpose: that Zaccheus, being a man of low stature,
and having a mind to see Christ, ran before and climbed up into a sycamore tree;
and our Saviour knowing his good desires, called to him, "`Zaccheus, come down,
this day is salvation come to your house.`"
Thus, Zaccheus was like some in our day, who are climbing up into the tree of knowledge,
thinking to find Christ there.
But the word now is, "`Zaccheus come down, come down;
for '`that which is to be known of God, is manifested within.`'`"^
footnote:[Romans 1:19]
This, with more to the same purpose, was spoken in such authority,
that when my father came home, he told my mother he had seen Richard Farnsworth,
who had spoken to his condition as if he had known him from his youth.
From this time forward, my father patiently bore the cross.

Afterwards,
when it pleased God to communicate to him a portion
of the knowledge of His blessed Truth,
a necessity was laid upon him one first-day morning
to go to the public worship house in Cirencester,
in the time of worship, not knowing what might be required of him there.
He went, and standing with his hat on, the priest was silent for some time;
but being asked why he did not go on, he answered,
he could not continue while that man stood with his hat on.
Upon this some took my father by the arm and led him into the street,
staying at the door to keep him out; but after waiting a little in stillness,
he found himself clear and passed away.
As he passed the market-place, the tie of his shoe slackened;
and while he stooped down to fasten it,
a man came behind him and struck him on the back a hard blow with a stone, saying,
"`There, take that for Jesus Christ`'s sake!`"
He answered, "`So I do,`" not looking back to see who it was,
but quietly going on his way.
A few days after a man came and asked him forgiveness;
telling him he was the unhappy man that gave him the blow on his back,
and he could have no rest since he had done it.

Not long after, three Friends came that way, who found themselves under the like concern,
namely: Robert Silvester, Philip Grey and Thomas Onyon.
These standing in the steeple-house with their hats on, though they said nothing,
the priest was silent; and being asked if he was not well, he answered,
he could not go forward while those dumb dogs stood there;
wherefore the people dragged them out.
The priest afterwards informing a justice that they had interrupted him in divine service,
they were bound over until the quarter sessions.
My father, at their desire, accompanied them to the court sessions;
and when they were called and the priest had accused them, the bench, in a rage,
without asking them any questions, ordered their court order to be made out.

This unjust and illegal proceeding kindled my father`'s zeal,
insomuch that he stepping forward, called to the justices, saying:
"`Are not those who sit on the bench sworn to do justice?
Is there not a man among you that will do the thing that is right?`"
Whereupon John Stephens, of Lipeat, then chairman, cried out, "`Who are you, sirrah?^
footnote:[Sirrah was a term used to address inferiors,
and often used as an expression of contempt.]
What is your name?`"
My father telling him his name, he said, "`I am glad I have you here;
I have heard of you--you deserve a dungeon:
there is many an honester man than you hanged!`" "`It may be so,`" answered my father;
"`but what do you think becomes of those who hang honest men?`"
The justice replied, "`I will send you to prison;
and if any insurrection or tumult be in the land,
I will come and cut your throat first with my own sword, for I fear to sleep in my bed,
lest such fanatics should come and cut my throat;`" and snatching up a ball of wax,
he violently threw it at my father, who avoided the blow by stepping aside.
Their court orders were then made, and they were all sent to prison.

The same evening my great uncle Solliss, who was one of the justices on the bench,
came to the prison, and calling for my father,
asked him if he was willing to have his liberty to go home to his wife and family.
"`Upon what terms, uncle?`"
said my father.

[.discourse-part]
__Justice Solliss:__ "`Upon such terms that the jailer open the door and let you out.`"

[.discourse-part]
__John Roberts:__ "`What! without entering into any recognizance?`"

[.discourse-part]
__Justice Solliss:__ "`Yes.`"

[.discourse-part]
__John Roberts:__ "`Then I accept my liberty.
But I wonder, uncle,
how you and several others could sit upon the bench as with your thumbs in your mouths,
when you should speak a word in behalf of the innocent.`"

[.discourse-part]
__Justice Solliss:__ "`You must learn to live under a law.
And if you will accept your liberty till next sessions, you may have it; if not,
stay where you are.`"

[.small-break]
'''

So they parted; and on the morrow my father went home, having also the jailer`'s leave.

In the night a concern came upon him with such weight,
that it made him tremble till the bed shook under him.
My mother asking the reason of it, he answered, "`the Lord requires hard things of me:
if it would please him,
I had rather lay down my life than obey Him in what he requires at my hands.`"
To which my mother replied; "`If you are fully persuaded the Lord requires it of you,
you must not disobey Him;
for He will require nothing of us but what He will enable us to go through;
therefore we have good cause to trust in him.`"
On which he said, "`I must go to this John Stephens, who is my great enemy,
and sent me to prison, where he said he would secure me;
and as my uncle Solliss in kindness has given me leave to come home,
I can expect no favour from him,
if I now go and run myself into the mouth of my adversary; but I must go,
whatever I suffer.`"
He arose and prepared for his journey, but dared eat or drink nothing.
When he mounted his horse, the command of the Lord was unto him, "`Remember Lot`'s wife:
look not back.`"

So on he rode very cheerfully eight or nine miles,
till he came within sight of the justice`'s house, and then he let in the reasoner,
who reasoned him out of all his courage,
presenting to his mind that his uncle Solliss and his neighbours
would say he had no regard for his wife and family,
thus to push himself into the hands of his greatest enemy.
This brought such a cloud over his mind,
that he alighted off his horse and sat down upon the ground,
to spread his cause before the Lord.
After he had waited some time in silence, the Lord appeared and dissipated the cloud,
and His word was to him, "`Go, and I will go with you,
and will give you a threshing instrument, and you shall thresh the mountains.`"
Then he was exceedingly overcome with the love of God; and I have often heard him say,
he was filled like a vessel that needed vent, and said in his heart,
"`Your presence is enough,`" proceeding to the house with great satisfaction.
It being pretty early in the morning, and seeing the stable door open,
he went to the groom, and desired him to put up his horse.
While this was doing, the justice`'s son and his clerk came up, the latter roughly said,
"`I thought you had been put in Gloucester, castle.`"

[.discourse-part]
__John Roberts:__ "`So I was.`"

[.discourse-part]
__Clerk:__ "`And how did you come out?`"

[.discourse-part]
__John Roberts:__ "`When you have authority to demand it, I can give you an answer;
but my business is with your master, if I may speak with him.`"

[.discourse-part]
__Clerk:__ "`You may, if you will promise to be civil.`"

[.discourse-part]
__John Roberts:__ "`If you see me uncivil, I desire you to tell me of it.`"

[.small-break]
'''

They went in; and my father following them, they bid him take a seat in the hall,
and they would acquaint the justice of his being there.
He was soon called in; and my father no sooner saw him,
but he believed the Lord had been at work upon him; for,
as he had behaved to him with the fierceness of a lion before,
he now appeared like a lamb, meeting him with a pleasant countenance,
and taking him by the hand.
He said, "`Friend Haywood, how do you do?`"
My father answered, "`Pretty well;`" and then proceeded thus;
"`I have come in the fear and dread of heaven,
to warn you to repent of your wickedness with speed,
lest the Lord cut the thread of your life, and send you to the pit that is bottomless.
I have come to warn you, in great love, whether you will hear or forbear,
and to preach the everlasting gospel unto you.`"
The justice replied, "`You are a welcome messenger to me,
that is what I have long desired to hear.`"
"`The everlasting gospel`" returned my father "`is
the same that God sent his servant John to declare,
when he saw an angel flying through the midst of heaven, saying with a loud voice,
'`Fear God and give glory to his name, and worship him who made heaven and earth,
the sea, and the fountains of water.`'`"

The justice then caused my father to sit down by him on a couch; and said,
"`I believe your message is of God, and I receive it as such.
I am sorry I have done you wrong; and I will never wrong you more.
I would pray you to forgive me, and to pray to God to forgive me.`"
After much more discourse,
he offered my father the best entertainment his house afforded;
but my father excused himself from eating or drinking with him at that time,
expressing his kind acceptance of his love; and so in much love they parted.

The same day William Dewsberry had appointed a meeting at Tedbury; where my mother went.
But she was so concerned on account of my father`'s exercise,
that she could receive little benefit from the meeting.
After the meeting was ended, William Dewsberry walked to and fro in a long passage,
groaning in spirit; and by and by came up to my mother,
and though she was a stranger to him, he laid his hand upon her head, and said, "`Woman,
your sorrow is great; I sorrow with you.`"
Then walking a little to and fro, as before, he came to her again, and said,
"`Now the time is come, that those who marry, must be as though they married not,
and those who have husbands, as though they had none;
for the Lord calls for all to be offered up.`"
By this she saw the Lord had given him a sense of her great burden;
for she had not uncovered her exercise to any; and it gave her such ease in her mind,
that she went home rejoicing in the Lord.
She no sooner got home, but she found my father returned from justice Stephens of Lipeat,
where his message was received in such love, as was far from their expectation.
The sense of this broke them into tears, in consideration of the great goodness of God,
in so eminently making way for, and helping them that day.

At the next sessions my father and the three Friends appeared in court; where,
as soon as justice Stephens spied them, he called to my father, and said, "`John,
I accept of your appearance, and discharge you, and the court discharges.
You may go about your business.`"
But my father thinking his work not done, did not hasten out of court.
Upon which the clerk demanded his fees.
"`What!
Do you mean money?`"
said my father.
"`Yes, what do you think I mean?`"
says the clerk.
My father replied, "`I do not know that I owe any man here anything but love,
and must I now purchase my liberty with money?
I do not accept it on such terms.`"

[.discourse-part]
__Clerk:__ (to the chairman.) "`May it please your worship,
John will not pay the fees of the court.`"

[.discourse-part]
__John Roberts:__ "`I do not accept my liberty on such terms.`"

[.small-break]
'''

Then he was ordered to prison with the three Friends.
But in the evening the clerk discharged them,
and ever after carried himself very kindly to my father.

He was afterwards cast into prison at Cirencester, by George Bull,
vicar of Upper Siddington, for tithes; where was confined at the same time,
upon the same account, Elizabeth Hewlings, a widow of Amney, near Cirencester.
She was a good Christian and so good a midwife,
that her confinement was a loss to that side of the country, insomuch, that lady Dunch,
of Down-Amney,
thought it would be an act of charity to the neighbourhood to purchase her liberty,
by paying the priest`'s demand; which she did.
She likewise came to Cirencester in a coach; and sent her footman, Alexander Cornwall,
to the prison to bring Elizabeth to her.
While Elizabeth was making ready to go with the man,
my father and he fell into a little discourse.
He asked my father his name, and where his home was; and, when my father had told him,
replied, "`What?
Are you that John Haywood of Siddington, who keeps great conventicles at your house?
My father answered, "`The church of Christ often meets at my house.
I suppose I am the man you mean.`"
"`I have often,`" replied Cornwall, "`heard my lady speak of you,
and I am sure she would gladly be acquainted with you.`"

When he returned to his lady, he told her he had met with such a man in the prison,
as he believed she would not desire to lie in prison for conscience-sake;
informing her who he was.
She immediately bid him to go back and fetch him to her.
Accordingly he came to the jail, and told my father his lady wanted to speak to him.
My father answered, "`If any body would speak with me, they must come where I am;
for I am a prisoner.`"
"`Oh,`" said Cornwall, "`I will get leave of the jailer for you to go;`" which he did.
And when they came before the lady, she put on a majestic air,
to see how the Quaker would greet her.

My father went up towards her, and bluntly said, "`Woman, do you wish to speak with me?`"

[.discourse-part]
__Lady:__ "`What is your name.`"

[.discourse-part]
__John Roberts:__ "`My name is John Roberts,
but I am commonly known by the name of John Haywood in the place where I live.`"

[.discourse-part]
__Lady:__ "`Where do you live?`"

[.discourse-part]
__John Roberts:__ "`At a village called Siddington, about a mile distant from this town.`"

[.discourse-part]
__Lady:__ "`Are you the man that keeps conventicles at your house?`"

[.discourse-part]
__John Roberts:__ "`The church of Christ does often meet at my house.
I presume I am the man that you mean.`"

[.discourse-part]
__Lady:__ "`What do you lie in prison for?`"

[.discourse-part]
__John Roberts:__ "`Because, for conscience-sake,
I cannot pay an hireling priest what he demands of me; therefore he,
like the false prophets of old, prepares war against me,
because I cannot put into his mouth.`"

[.discourse-part]
__Lady:__ "`By what I have heard of you, I took you to be a wise man,
and if you could not pay him yourself, you might let somebody else pay him for you.`"

[.discourse-part]
__John Roberts:__ "`That would be underhand dealing, and I had rather pay him myself,
than be such a hypocrite.`"

[.discourse-part]
__Lady:__ "`Then suppose some neighbour or friend should pay him for you, unknown to you,
you would choose not to lie in prison when you might have your liberty?`"

[.discourse-part]
__John Roberts:__ "`I am very well content where I am,
till it shall please God to make way for my freedom.`"

[.discourse-part]
__Lady:__ "`I have a mind to set you at liberty, that I may have some of your company,
which I cannot well have while you are in the prison.`"

[.small-break]
'''

Then, speaking to her man, she bid him go to the priest`'s attorney,
and tell him she would satisfy him,
and then pay the jailer his fees and get a horse
for my father to go to Down-Amney with her.

[.discourse-part]
__John Roberts:__ "`If you are a charitable woman, as I take you to be,
there are abroad in the world many real objects of charity on whom to bestow your bounty;
but to feed such devourers as these, I do not think to be charity.
They are like Pharaoh`'s lean kine; they eat up the fat and the goodly,
and look not a whit the better.`"

[.discourse-part]
__Lady:__ "`Well; I would have you get ready to go with us.`"

[.discourse-part]
__John Roberts:__
"`I do not know you are likely to have me when you have bought and paid for me;
for if I may have my liberty,
I shall think it my place to be at home with my wife and family.
But if you desire it, I will come and see you at Down-Amney some other time.`"

[.discourse-part]
__Lady:__ "`That will suit me better.
But set your time, and I will lay aside all other business to have your company.`"

[.discourse-part]
__John Roberts:__ "`If it please God to give me life, health and liberty,
I intend to come on seventh-day next, the day you call Saturday.`"

[.discourse-part]
__Lady:__ "`Is that as far as you are accustomed to promise?

[.discourse-part]
__John Roberts:__ "`Yes.`"

[.small-break]
'''

According to his appointment, my father went;
and found her very inquisitive about the things of God,
and very attentive to the truths he delivered.
She engaged him likewise a second time, and treated him with abundance of regard.
A third time she bid her man Cornwall to go to him and desire
him to appoint a day when he would pay her another visit;
and then also ordered her man to go to the priest Careless, of Cirencester,
and desire him to come and take a dinner with her at the same time;
and did not let either of them know the other was to be there.

On the day appointed my father went; and when he had got within sight of her house,
he heard a horse behind him, and looking back, he saw the priest following him,
which made him conclude the lady had planned to bring them together.
When the priest came up to him, he said, "`Well John, how far are you going this way?`"
My father answered, "`I believe we are both going to the same place.`"
"`What! said priest Careless, are you going to the great house?`"
"`Yes,`" said my father.
"`Come on then, John,`" said he.
So then they went in together.
And the lady being ill in bed, a servant went up and informed her they were come.
"`What! said she, did they come together?`"
"`Yes,`" answered the servant.
"`I admire at that, said she.
But do you beckon John out, and bring him to me first up the back stairs.`"
When my father came up, she told him she had been very ill in a fit of the stone,
and said, "`I have heard you have done good with many distempers.`"

[.discourse-part]
__John Roberts:__ "`I confess I have; but to this of the stone I am a stranger.
Indeed I once knew a man, who lived at ease and fared delicately, as you may do,
and while he continued in that practice he was much afflicted with that distemper.
But it pleased the Lord to visit him with the knowledge of his blessed truth,
which brought him to a more regular and temperate life,
and this preserved him more free from it.`"

[.discourse-part]
__Lady:__ "`Oh!
I know what you aim at.
You want to have me a Quaker.
And I confess, if I could be such a one as you are, I would be a Quaker tomorrow.
But now I understand Mr. Careless is below;
and though you are men of different persuasions, I account you both wise and godly men,
and some moderate discourse of the things of God
between you both I believe would do me good.`"

[.discourse-part]
__John Roberts:__ "`If he ask me any questions, as the Lord shall enable me,
I shall endeavour to give him an answer.`"

[.small-break]
'''

She then had the parson up; and after a compliment or two, she said,
"`I made bold to send for you to take an ordinary dinner with me,
though I am disappointed of your company by my illness.
But John Haywood and you, being persons of different persuasions,
though I believe both good Christians,
if you would soberly ask and answer each other a few questions, it would divert me;
so that I should be less sensible of the pains I lie under.`"

[.discourse-part]
__Priest:__ "`May it please your ladyship, I see nothing in that.`"

[.discourse-part]
__Lady:__ "`Please Mr. Careless, ask John some questions.`"

[.discourse-part]
__Priest:__ "`It will not edify your ladyship;
for I have discoursed John and several others of his persuasion various times,
and I have read their books, and all to no purpose; for they sprang from the Papists,^
footnote:[i.e. Roman Catholics]
and hold the same doctrine they do.
Let John deny it if he can.`"

[.discourse-part]
__John Roberts:__ "`I find you are setting us out in very black characters,
with design to affright me; but therein you will be mistaken.
I advise you to say no worse of us than you can prove,
and then make us as black as you can.
And if you can prove me a Papist in one thing,
with the help of God I will prove you like them in ten.
And this woman who lies here in bed shall be judge.`"

[.discourse-part]
__Priest:__ "`The Quakers hold that damnable doctrine and dangerous tenet,
of perfection in this life; and so do the Papists.
If you go about to deny it, John, I can prove you hold it.`"

[.discourse-part]
__John Roberts:__ "`I doubt you are now going about to belie the Papists behind their backs,
as you have heretofore done by us.
For, by what I have learnt of their principles,
they do not believe a state of freedom from sin and
acceptance with God possible on this side the grave;
and therefore they have imagined to themselves a place of purgation after death.
But whether they believe such a state attainable or no, I do.`"

[.discourse-part]
__Priest:__ "`May it please your ladyship, John has confessed enough out of his own mouth;
for that is a damnable doctrine and dangerous tenet.`"

[.discourse-part]
__John Roberts:__ "`I would ask you one question; do you believe in a purgatory?`"

[.discourse-part]
__Priest:__ "`No.`"

[.discourse-part]
__John Roberts:__ "`Then the Papists, in this case, are wiser than you.
They acknowledge the saying of Christ, who told the unbelieving Jews,
'`If you die in your sins, where I go you cannot come.`'^
footnote:[John 8:21-24]
But by your discourse,
you and your followers must necessarily go headlong to destruction;
since you neither own a place of purgation after death,
nor such a preparation for heaven to be possible in this life,
as is absolutely necessary.
The Scripture you know tells us that where death leaves us, judgment will find us,
and '`If a tree falls towards the north or south, in the place where the tree falls,
there it shall lie.`'^
footnote:[Ecclesiastes 11:3]
And since no unclean thing can enter the kingdom of heaven, please tell this poor woman,
whom you have been preaching to for your belly, whether ever, or never,
she must expect to be freed from her sins, and made fit for the kingdom of heaven;
or whether the blind must lead the blind till both fall into the ditch.`"

[.discourse-part]
__Priest:__ "`No, John, you mistake me:
I believe that God Almighty is able of his great mercy to forgive persons their sins,
and fit them for heaven a little before they depart this life.`"

[.discourse-part]
__John Roberts:__ "`I believe the same.
But, if you will limit the holy One of Israel,
how long will you give the Lord to make fit a person for His glorious kingdom?`"

[.discourse-part]
__Priest:__ "`It may be an hour or two before they die.`"

[.discourse-part]
__John Roberts:__ "`My faith is a day or two, as well as an hour or two.`"

[.discourse-part]
__Priest:__ "`I believe so too.`"

[.discourse-part]
__John Roberts:__ "`Or a week or two.`"

[.small-break]
'''

And my father carried it to a month or two;
and so gradually till he brought it to seven years,
the priest confessing he believed the same.
On which my father thus proceeded:

[.discourse-part]
"`How could you accuse me of Popery^
footnote:[Roman Catholicism]
in holding this doctrine, which you yourself have confessed to believe too?
If I am like a Papist, you are as well, by your own confession, as like a Papist as I am.
And if it be a damnable doctrine and dangerous tenet in the Quakers,
is it not the same in yourself?
You told me I mistook you;
but have you not mistaken yourself in condemning
your own acknowledged opinion when uttered by me!
But notwithstanding you have failed in making me out to be a Papist in this particular,
can you do it in anything else?`"

[.offset]
Upon this the priest being mute, my father thus proceeded:

[.discourse-part]
"`Well! though you have failed in proving me like them,
it need not hinder me from showing you to be so in many things.
For instance, you build houses and consecrate them, calling them churches,
as do the Papists.
You hang bells in them, and consecrate them, calling them by the names of saints;
so do they.
The pope and the priests of the Roman church wear surplices, gowns, cassocks, etc.,
calling them their ornaments; here you do the like;
and do you not also call them your ornaments?
You consecrate the ground where you inter your dead, calling it holy ground; so do they.
In short, you are like a Papist in so many things,
he need be a wise man to distinguish between them and you.`"

[.small-break]
'''

At this the priest appeared uneasy; and said to the lady, "`Madam,
I must beg your excuse; for there is to be a lecture this afternoon,
and I must be there.`"
She pressed him to stay for dinner, but he earnestly desired to be excused.
So a slice or two being cut off the roast, he ate and took his leave.

The lady then said to my father, had she not seen it,
she could not have believed Mr. Careless could have
been so foiled in discourse by any man;
"`For,`" said she, "`I accounted him as sound and orthodox a divine as any was;
but now I must tell you, I am so far of your opinion,
that if you will let me know when you have a meeting at your house,
and somebody to preach, not a silent meeting, I will come and hear them myself.`"
My father answered, he expected she would be as good as her word.

Not long after came two friends to my father`'s house,
and though the weather was very severe,
he found he could not be easy without acquainting her with it.
So he went to her house, but she seemed a little surprised; saying,
"`What is your will now, John?`"
He informed her of the two friends, and their intention of having a meeting at his house.
"`How can you expect,`" said she, "`I should go out in such weather as this?
You know I seldom stir out of my chamber, and to go so far may endanger my health.`"
My father returned, "`I would not have you make excuses, as some of old did,
and were not found worthy.
You know time is not ours, and we know not whether we may have the like opportunity again.
The snow need not much incommode you; you may be quickly in your coach,
and putting up the glasses, may be pretty warm; and when you come to my house,
I know my wife will do her best for you.`"
So she ordered her coach and six horses to be got ready,
for the distance was seven miles, saying, "`John is like death, he will not be denied.`"

My father came along with her; and during the time of silence in the meeting,
she appeared somewhat restless;
but was very attentive while either of the friends were speaking.
She was very well pleased after the meeting, and sat at a table with the friends.
While the rest sat silent, she would be frequently whispering to my mother,
till one of them spoke a few words before the meal.
She was ashamed, and told my mother, when she was among the great,
she was accounted a wise woman; "`But now,`" said she, "`when I am among you Quakers,
I am a very fool.`"
Presently after dinner she returned home,
and came several times to the meeting afterwards;
and I am fully persuaded she was convinced of the truth; but going up to London once,
she was there taken ill, and died.

Her man, Alexander Cornwall, was convinced of the truth,
and was afterwards a prisoner with my father in Gloucester castle;
where the jailer was very cruel to them,
sometimes putting them into the common jail among felons,
and other times he would hire a tinker,^
footnote:[A mender of brass kettles, pans and the like.]
who lay in jail for his fees, to trouble them in the night, by playing on his flute.
One time in particular,
my father being concerned to speak to him in the dread and power of God,
it struck him to such a degree, that he dropped the instrument out of his hand,
and would never take it into his hand upon that occasion anymore.
When the jailer asked him why he discontinued it, he answered,
"`They are the servants of the living God, and I will never play more to disturb them,
not if you hang me up at the door for it.`"
"`What!`" said the jailer, "`are you bewitched too!
I will turn you out of the castle.`"
Which he did; and the Friends who were there prisoners, raised him some money,
clothed him, and away he went.

Some time after this, my father had three conferences with Nicholson,
bishop of Gloucester, which took place in the following manner.
An officer came to cite my father to appear at the bishop`'s court;
but he told my father he could not encourage him to come, lest they should ensnare him,
and send him to prison.
At the same time they cited an old servant of my father`'s, named John Overall.
My father went at the time appointed, without his servant;
and when his name was called over, he answered to it.
The discourse that occurred was in substance as follows:

[.discourse-part]
__Bishop:__ "`What is your name?`"

[.discourse-part]
__John Roberts:__ "`I was just called by my name, and answered to it.`"

[.discourse-part]
__Bishop:__ "`I desire to hear it again.`"

[.discourse-part]
__John Roberts:__ "`My name is John Roberts.`"

[.discourse-part]
__Bishop:__ "`Well, you were born Roberts; but you were not born John.
Pray, who gave you that name?`"

[.discourse-part]
__John Roberts:__ "`You have asked me a very hard question,
my name being given to me before I was capable of remembering who gave it.
But I believe it was my parents,
they being the only persons who had a right to give me my name.
That name they always called me by, and to that name I always answered;
and I believe none need call it in question now.`"

[.discourse-part]
__Bishop:__ "`No, no, but how many children have you?`"

[.discourse-part]
__John Roberts:__ "`It has pleased God to give me six children;
three of whom He pleased to take from me; the other three are still living.`"

[.discourse-part]
__Bishop:__ "`And how many of them have been bishoped?^
footnote:[Formally confirmed into membership in the church of England.]`"

[.discourse-part]
__John Roberts:__ "`None that I know of.`"

[.discourse-part]
__Bishop:__ "`What reason can you give for that?`"

[.discourse-part]
__John Roberts:__ "`A very good one, I think;
most of my children were born in Oliver Cromwell`'s days,
when bishops were out of fashion.`"
(At this the court fell a laughing.)

[.discourse-part]
__Bishop:__ "`But how many of them have been baptized?`"

[.discourse-part]
__John Roberts:__ "`What do you mean by that?`"

[.discourse-part]
__Bishop:__ "`What, do not you own baptism?`"

[.discourse-part]
__John Roberts:__ "`Yes; but perhaps we may differ in that point.`"

[.discourse-part]
__Bishop:__ "`What baptism do you own?
That of the Spirit, I suppose.`"

[.discourse-part]
__John Roberts.__
"`Yes.
What other baptism should I own?`"

[.discourse-part]
__Bishop:__ "`Do you own but one baptism?`"

[.discourse-part]
__John Roberts:__ "`If one be enough, what need is there of any more!
The apostle said, '`One Lord, one faith, one baptism.`'`"^
footnote:[Ephesians 4:5]

[.discourse-part]
__Bishop:__ "`What do you say about the baptism of water?`"

[.discourse-part]
__John Roberts:__ "`I say there was a man sent from God, whose name was John,
who had a real commission for it; and he was the only man that I read of,
who was empowered for that work.`"

[.discourse-part]
__Bishop:__ "`But what if I make it appear to you,
that some of Christ`'s disciples themselves baptized with water,
after Christ`'s ascension?`"

[.discourse-part]
__John Roberts:__ "`I suppose that is no very difficult task; but what is that to me?`"

[.discourse-part]
__Bishop:__ "`Is it nothing to you what Christ`'s disciples themselves did?`"

[.discourse-part]
__John Roberts:__ "`Not in everything; for Paul, that eminent apostle, who,
I suppose you will grant,
had as extensive a commission as any of the rest of the apostles; no, he says himself,
he was not a whit behind the chiefest of them,
and yet he honestly confesses he had no commission to baptize with water;
and further says, '`I thank God I baptized none but`' such and such; for, says he,
'`I was not sent to baptize, i.e., with water,
but to preach the gospel.`' And if he was not sent, I would soberly ask,
who required it at his hands?
Perhaps he might have as little thanks for his labour as you may have for yours;
and I would willingly know who sent you to baptize?`"

[.discourse-part]
__Bishop:__ "`This is not our present business.
You are brought here for not coming to church.
What say you to that?`"

[.discourse-part]
__John Roberts:__ "`I desire to see my accusers.`"

[.discourse-part]
__Bishop:__ "`It is the minister and the church wardens.
Do you deny it?`"

[.discourse-part]
__John Roberts:__ "`Yes I do; for it is always my principle and practice to go to church.`"

[.discourse-part]
__Bishop:__ "`And do you go to church?`"

[.discourse-part]
__John Roberts:__ "`Yes, and sometimes the church comes to me.`"

[.discourse-part]
__Bishop:__ "`The church comes to you: I do not understand you, friend.`"

[.discourse-part]
__John Roberts:__ "`It may be so:
it is often for lack of a good understanding that the innocent are made to suffer.`"

[.discourse-part]
__Officer:__ "`My lord, he keeps meetings at his house, and he calls that a church.`"

[.discourse-part]
__John Roberts:__ "`No; I no more believe my house to be a church,
than I believe what you call so to be one.
I call the people of God the church of God,
wheresoever they are met to worship Him in spirit and in truth.
And when I say the church comes to me, I mean the assembly of such worshippers,
who frequently meet at my house.
I do not call that a church which you do, which is made of wood and stone,
that is but the workmanship of men`'s hands,
whereas the true church consists of living stones,
and is built up by Christ a spiritual house to God.`"

[.discourse-part]
__Bishop:__ "`We call it a church figuratively, meaning the place where the church meets.`"

[.discourse-part]
__John Roberts:__ "`I fear you call it a church hypocritically and deceitfully,
with design to awe the people into a veneration for the place, which is not due to it,
as though your consecrations had made that house holier than others.`"

[.discourse-part]
__Bishop:__ "`What do you call that which we call a church?

[.discourse-part]
__John Roberts:__ "`It may properly enough be called a mass house,
it being formerly built for that purpose.`"

[.discourse-part]
__Officer:__ "`Mr. Haywood,
it is expected you should show more respect than
you do in this place by keeping on your hat.`"

[.discourse-part]
__John Roberts:__ "`Who expects it`"

[.discourse-part]
__Officer:__ "`My lord the Bishop`"

[.discourse-part]
__John Roberts:__ "`I expect better things from him.`"

[.discourse-part]
__Bishop:__ "`No, no; keep on your hat: I do not expect it from you.
+++[+++A little after, the bishop said:]
"`Well friend, this is not a convenient time for you and I to dispute;
but I may take you to my chamber and convince you of your errors.`"

[.discourse-part]
__John Roberts:__ "`I should take it kindly of you, or any other man,
to convince me of any errors that I hold; and then would hold them no longer.`"

[.discourse-part]
__Bishop:__ "`Call some others.`"

[.small-break]
'''

Then my father`'s servant was called; who not appearing, the officer said, "`Mr. Haywood,
is John Overall here?`"

[.discourse-part]
__John Roberts:__ "`I believe not.`"

[.discourse-part]
__Bishop:__ "`What is the reason he is not here?`"

[.discourse-part]
__John Roberts:__ "`I think there are very good reasons for his absence.`"

[.discourse-part]
__Bishop:__ "`What are they?
may not I know?`"

[.discourse-part]
__John Roberts:__ "`In the first place, he is an old man,
and not of ability to undertake such a journey, except it was upon a very good account.
In the second place, he is my servant;
and I cannot spare him out of my business in my absence.`"

[.discourse-part]
__Bishop:__ "`Why does he not go to church then?`"

[.discourse-part]
__John Roberts:__ "`He does go to church with me.`"

[.offset]
At this the court fell a laughing.

[.discourse-part]
__Bishop:__ "`Call somebody else.`"

[.small-break]
'''

Then a Baptist preacher was called, who seeing the bishop`'s civility to my father,
in allowing him to keep on his hat, thought to take the same liberty.
But the bishop put on a stern countenance, and said,
"`Do not you know this is the king`'s court,
and that I sit here to represent his majesty`'s person?
And do you come here in an uncivil and irreverent manner,
in contempt of his majesty and his court, with your hat on?
I confess there are some men in the world who make
the putting off their hats a matter of conscience,
to whom we ought to have some regard.
But for you, who can put it off to every mechanic you meet, to come here,
in contempt of authority, with it on, I will assure you, friend,
you shall prosper no better for it.`"
I heard my father say, these words came so honestly from the bishop,
that it did him good to hear him.
The Baptist then taking off his hat, said, "`May it please you, my lord,
I have not been well in my head.`"

[.discourse-part]
__Bishop:__ "`Why, you have got a cap on; no,
you have two caps on! +++[+++He had a black one over a white one.]
What is your reason for denying your children that holy ordinance of baptism?`"

[.discourse-part]
__Baptist:__ "`May it please you, my lord, I am not well satisfied about it.`"

[.discourse-part]
__Bishop:__ "`What is the ground of your dissatisfaction!
Did you ever see a book I published, entitled, '`The order of Baptism?`'`"

[.discourse-part]
__Baptist:__ "`No, my lord.`"

[.discourse-part]
__Bishop:__ "`I thought so.`"

[.small-break]
'''

Then telling how and where he might get it, he gave him a space of time to peruse it;
and told him if that would not satisfy him, to come to him,
and he would give him full satisfaction.

Some time after this the bishop sent his bailiff to take my father;
but he was then gone to Bristol with George Fox.
The officers came several times and searched the house for him,
pretending they only wanted him for a small trespass, which would soon be made up,
if they could see him.
My mother answered,
she did not believe any neighbour he had would trouble him upon such an account;
for if by chance any of his cattle trespassed upon any,
he would readily make them satisfaction,
without further trouble (which they very well knew).
However, she always treated them civilly, and frequently set food and drink before them.
My father staying away longer than was expected,
they imagined he absconded for fear of them; and therefore offered my mother,
if she would give them twenty shillings, to let him come home for a month.
But she told them she knew of no wrong he had done to any man,
and therefore would give them no money; for that would imply a consciousness of guilt.
"`But,`" said she, "`if my enemy hunger, I can feed him; and if he thirst,
I can give him drink.`"
Upon this they flew into a rage, and said, they would have him if he were above ground;
for none could pardon him but the king.
My father returning home through Tedbury,
was there informed that the bailiffs had been about
his house almost ever since he went from home.
He therefore planned to come home after daylight.
When he came into his own grounds, the moon shining bright, he spied the shadow of a man,
and asked, "`Who is there?`"
"`It is I,`" said the man.

[.discourse-part]
__John Roberts:__ "`Who?
Sam Stubbs?`"
(He was a bailiff.)

[.discourse-part]
__Sam Stubbs:__
"`Yes, master.`"

[.discourse-part]
__John Roberts:__ "`Have you anything against me?`"

[.discourse-part]
__Sam Stubbs:__
"`No, master: I might; but I would not meddle: I have wronged you enough already;
God forgive me.
But those who now lie in wait for you are the Paytons, my lord bishop`'s bailiffs.
I would not have you fall into their hands, for they are merciless rogues.
I would have you, master, take my counsel.

[.small-break]
'''

My father came home, and desired us not to let the bailiffs in upon him that night,
that he might have an opportunity of taking counsel on his pillow.

In the morning he told my mother what he had seen that night in a vision.
"`I thought,`" said he, "`I was walking a fine pleasant green way; but it was narrow,
and had a wall on each side of it.
In my way lay something like a bear, but more dreadful.
The sight of him put me to a stand.
A man seeing me surprised, came to me with a smiling countenance, and said.
'`Why are you afraid, friend?
he is chained, and cannot hurt you.`' I thought I made answer.
'`The way is so narrow,
I cannot pass by but he may reach me.`' '`Do not be afraid,`' said the man,
'`he cannot hurt you.`' I saw he spoke in great good will,
and thought his face shone like the face of an angel.
Upon this I took courage, and stepping forward, laid my hand upon his head.`"
The construction he made of this dream to my mother was: Truth is a narrow way,
and this bishop lies in my way; I must go to him, whatever I suffer.
So he arose and set forward, and called upon Amariah Drewett, a Friend of Cirencester,
to accompany him.

When they came to the bishop`'s house at Cleve, near Gloucester,
they found a butcher`'s wife, of Cirencester, who had come to intercede for her husband,
who was put into the bishop`'s court for killing cattle on first-days.
Two young men of the bishop`'s attendance were asking her if she knew John Haywood?
She answered, "`Yes, very well.`"
"`What sort of man is he?`"
said they.
"`A very good man,`" said she, "`setting aside his religion;
but I have nothing to say to that.`"
One of them said he would give five shillings to see him; the other offered eight.
Upon which my father stepped up to them; but they said not one word to him.
One of them presently informed the bishop he was come.
Whereupon the bishop dismissed his company, and led him up stairs.
My father found him seated in his chair, with his hat under his arm,
assuming a majestic air.
My father stood silent a while; and seeing the bishop did not begin with him,
he approached nearer, and thus said to him: "`Old man, my business is with you.`"

[.discourse-part]
__Bishop:__ "`What is your business with me?`"

[.discourse-part]
__John Roberts:__ "`I have heard you have sent out your bailiffs to take me;
but I rather chose to come myself, to know what wrong I have done you.
If it appear I have done you any, I am ready to make you satisfaction; but if,
upon inquiry, I appear to be innocent, I desire, for your own soul`'s sake,
you do not injure me.`"

[.discourse-part]
__Bishop:__ "`You are misinformed, friend; I am not your adversary.`"

[.discourse-part]
__John Roberts:__ "`Then I desire you to tell me who is my adversary,
that I may go and agree with him while I am in the way.`"

[.discourse-part]
__Bishop:__ "`The king is your adversary.
The king`'s laws you have broken, and to the king you shall answer; that is more.`"

[.discourse-part]
__John Roberts:__ "`Our subjection to laws is either active or passive.
So that if a man cannot, for conscience-sake, do the thing the law requires,
but passively suffers what the law inflicts, the law, I conceive,
is as fully answered as if he had actually obeyed.`"

[.discourse-part]
__Bishop:__ "`You are wrong in that too; for suppose a man steals an ox,
and then is taken and hanged for the fact; what restitution is that to the owner?`"

[.discourse-part]
__John Roberts:__ "`None at all.
But though it is no restitution to the owner, yet the law is satisfied.
Though the owner be a loser, the criminal has suffered the punishment the law inflicts,
as an equivalent for the crime committed.
But I hope you see the corruptness of such laws,
that put the life of a man upon a level with the life of a beast.`"

[.discourse-part]
__Bishop:__ "`What!
Do such men as you find fault with the laws?`"

[.discourse-part]
__John Roberts:__ "`Yes; and I will tell you plainly,
it is high time wiser men were chosen to make better laws.
For if this thief was taken and sold for a proper term, according to the law of Moses,
and the owner had four oxen given him for his ox, and four sheep for his sheep,
he would be satisfied, and the man`'s life would also be preserved, that he might repent,
and amend his ways.
But I hope you do not accuse me of having stolen any man`'s ox or ass.`"

[.discourse-part]
__Bishop:__ "`No, no; God forbid!`"

[.discourse-part]
__John Roberts:__ "`Then if you please to give me leave,
I will state a case more parallel to the matter in hand.`"

[.discourse-part]
__Bishop:__ "`You may.`"

[.discourse-part]
__John Roberts:__ "`There lived in days past, Nebuchadnezzar, king of Babylon,
who set up an image, and made a decree, that all who would not bow to it,
should be cast the same hour into a burning fiery furnace.
There were then three young men, who served the same God that I do now,
and these dared not bow down to it; but passively submitted their bodies to the flames.
Was not that a sufficient satisfaction to the unjust decree of the king?`"

[.discourse-part]
__Bishop:__ "`Yes.
God forbid it be seen as anything else!
For that command was to worship the workmanship of men`'s hands; which is idolatry.`"

[.discourse-part]
__John Roberts:__ "`Is that your judgment,
that to worship the workmanship of men`'s hands is idolatry?`"

[.discourse-part]
__Bishop:__ "`Yes, certainly.`"

[.discourse-part]
__John Roberts:__ "`Then give me leave to ask you,
by whose hands the common-prayer-book was made,
I am sure it was made by somebody`'s hands, for it could not make itself?`"

[.discourse-part]
__Bishop:__ "`Do you compare our common-prayer-book to Nebuchadnezzar`'s image?`"

[.discourse-part]
__John Roberts:__ "`Yes, I do: that was his image, and this is yours.
And be it known unto you, I speak in the dread of the God of heaven,
I no more dare bow to your common-prayer-book than the three
children could bow to Nebuchadnezzar`'s image.`"

[.discourse-part]
__Bishop:__ "`Yours is a strange upstart religion, of a very few years standing,
and you are grown so confident in it that there is no beating you out of it.`"

[.discourse-part]
__John Roberts:__ "`Out of my religion?
God forbid!
I was a long time seeking acquaintance with the living
God amongst the dead forms of worship,
and inquiring after the right way and worship of God, before I could find it; and now,
I hope neither you nor any man living shall be able to persuade me out of it.
But though you are an ancient man and a bishop,
I find you are very ignorant of the rise and antiquity of our religion.`"

[.discourse-part]
__Bishop:__ (Smiling) "`Do you Quakers claim antiquity for your religion?`"

[.discourse-part]
__John Roberts:__ "`Yes; and I do not question, but, with the help of God,
I can make it appear that our religion was many hundred
years before yours was thought of.`"

[.discourse-part]
__Bishop:__ "`You see I have given you liberty of discourse,
and have not sought to ensnare you in your words;
but if you can make the Quakers`' religion appear
to be many hundred years older than mine,
you will fair the better.`"

[.discourse-part]
__John Roberts:__ "`If I do not, I seek no favour at your hands, and in order to do it,
I hope you will give me liberty to ask a few sober questions.`"

[.discourse-part]
__Bishop:__ "`You may.`"

[.discourse-part]
__John Roberts:__ "`Then first I would ask you,
where was your religion in Oliver Cromwell`'s days?
The common-prayer-book had then become, (even among the clergy) like an old almanac,
very few regarding it in our country.
There were two or three priests who indeed stood honestly to their principles,
and suffered pretty much; but the far greater number turned with the tide.
And we have reason to believe,
that if Oliver would have put a Roman mass into their mouths,
they would have conformed even to that for their bellies.`"

[.discourse-part]
__Bishop:__ "`What would you have us do?
Would you have Oliver cut our throats?`"

[.discourse-part]
__John Roberts:__ "`No, by no means.
But what religion was it that you were afraid to venture your throats for?
Be it known unto you,
I ventured my throat for my religion in Oliver`'s days as I do now.`"

[.discourse-part]
__Bishop:__ "`And I must tell you,
though in Oliver`'s days I did not dare to own it as I do now,
yet I never owned any other religion.`"

[.discourse-part]
__John Roberts:__ "`Then I suppose you made it a matter of conscience;
and I should abundantly rather choose to fall into such a man`'s hands,
than into the hands of one who makes nothing a matter of conscience towards God,
but will conform to anything for his belly.
But if you did not think your religion worth venturing your throat for in Oliver`'s days,
I desire you to consider, it is not worth cutting other men`'s throats now,
for not conforming to it.`"

[.discourse-part]
__Bishop:__ "`You say right; I hope we shall be careful how we cut men`'s throats.
(Several others were now come into the room.) But you know
the common-prayer-book was before Oliver`'s days.`"

[.discourse-part]
__John Roberts:__ "`Yes; I have a great deal of reason to know that;
for I was bred up under a common-prayer priest, and a poor old drunken man he was.
Sometimes he was so drunk he could not say his prayers,
and at best he could barely say them;
though I think he was by far a better man than the one that is priest there now.`"

[.discourse-part]
__Bishop:__ "`Who is your minister now?`"

[.discourse-part]
__John Roberts:__ "`My minister is Christ Jesus, the minister of the everlasting covenant;
but the present priest of the parish is George Bull.`"

[.discourse-part]
__Bishop:__ "`Do you say that the drunken old man was better than Mr. Bull?
I tell you, I account Mr. Bull as sound, able,
and orthodox a minister as any we have among us.`"

[.discourse-part]
__John Roberts:__ "`I am sorry for that; for if he is one of the best of you,
I believe the Lord will not endure you long; for he is a proud, ambitious, ungodly man.
He has often sued me at law, and brought his servants to swear against me wrongfully.
His servants themselves have confessed to my servants, that I might have their ears;^
footnote:[The removal of a person`'s ears (called cropping)
was a common punishment under the law at this time.]
for their master made them drunk,
and then told them they were set down in the list as witnesses against me,
and they must swear to it: and so they did, and brought triple damages.
They likewise acknowledged they took tithes from my servant, threshed them out,
and sold them for their master.
They have also several times took my cattle out of my grounds,
drove them to fairs and markets, and sold them without giving me any account.`"

[.discourse-part]
__Bishop:__ "`I do assure you I will inform Mr. Bull of what you say.`"

[.discourse-part]
__John Roberts:__ "`Very well.
And if you please to send for me to face him,
I shall make much more appear to his face than I will say behind his back.`"

[.discourse-part]
__Bishop:__
"`But I remember you said you could make it appear
that your religion was long before mine;
and that is what I want to hear you make out.`"

[.discourse-part]
__John Roberts:__ "`Our religion, as you may read in the Scripture,
(John 4) was set up by Christ Himself, between sixteen and seventeen hundred years ago;
and He had full power to establish the true religion in His church,
when he told the woman of Samaria, that neither at that mountain, nor yet at Jerusalem,
was the place of true worship.
They worship they knew not what.
For, said he, '`God is a Spirit,
and they that worship him must worship him in spirit and in truth.`' This is our religion,
and has ever been the religion of all those who have worshipped
God acceptably through the several ages since,
down to this time;
and it will be the religion of the true spiritual worshippers of God to the world`'s end.
It is a religion performed by the assistance of the Spirit of God,
because God is a Spirit; a religion established by Christ himself, before the mass-book,
service-book, or directory, or any of those inventions and traditions of men,
which were set up in the night of apostasy.`"

[.discourse-part]
__Bishop:__ "`Are all the Quakers of the same opinion?`"

[.discourse-part]
__John Roberts:__ "`Yes, they are.
If any hold doctrines contrary to that taught by our Saviour to the woman of Samaria,
they are not of us.`"

[.discourse-part]
__Bishop:__ "`Do you own the trinity?`"

[.discourse-part]
__John Roberts:__ "`I do not remember such a word in the holy Scriptures.`"

[.discourse-part]
__Bishop:__ "`Do you own three persons?`"

[.discourse-part]
__John Roberts:__ "`I believe according to the Scripture,
that there are three that bear record in heaven, and that those three are One;
you may make as many '`persons`' of them as you can.
But I would soberly ask you,
since the Scriptures say the heaven of heavens cannot contain Him,
and that He is incomprehensible,
by what person or likeness can you comprehend the Almighty?`"

[.discourse-part]
__Bishop:__ "`Yours is the strangest of all persuasions;
for though there are many sects (which he named) and though
they and we differ in some circumstantial things,
yet in the fundamentals we agree as one.
But I observe, you of all others, strike at the very root and basis of our religion.`"

[.discourse-part]
__John Roberts:__ "`Are you sensible of that?`"

[.discourse-part]
__Bishop:__ "`Yes, I am.`"

[.discourse-part]
__John Roberts:__ "`I am glad of that; for the root is where there is rottenness,
and truth strikes at the very foundation thereof.
That little stone which Daniel saw cut out of the mountain without hands,
will overturn all in God`'s due time, though you have done all you can to support it.
But, as to those others you mention, there is so little difference between you,
that wise men wonder why you differ at all; only we read,
the beast had many heads and many horns, which push against each other.
And yet I am also fully persuaded,
that there are many true spiritual worshippers in this day in all persuasions.`"

[.discourse-part]
__Bishop:__
"`But you will not give us the same liberty you give a common
mechanic to call our tools by their own names.`"

[.discourse-part]
__John Roberts:__ "`I desire you to explain yourself.`"

[.discourse-part]
__Bishop:__ "`Why, you will give a carpenter leave to call his drill a drill,
and his chisel a chisel; but you call our church a mass-house.`"

[.discourse-part]
__John Roberts:__ "`I wish you were half so honest men as carpenters.`"

[.discourse-part]
__Bishop:__ "`Why?
Do you reproach us?`"

[.discourse-part]
__John Roberts:__ "`I have no desire to reproach you;
but I will endeavour to show you wherein you fall short of carpenters.
Suppose I had a son intended to learn the trade of a carpenter;
I contract with an honest man of that calling, for a certain quantity of money,
in order to teach my son his trade in such-and-such a term of years.
At the end of which term my son may be as good,
or perhaps a better workman than his master,
and he shall be at liberty from him to pursue the business for himself.
Now, will you be so honest as this carpenter?
You are men who claim to know more of light, life, and salvation,
and things pertaining to the kingdom of heaven, than we do.
I would ask in how long a time you would undertake to teach us as much as you know?
And what shall we give you, that we may be once free from our masters?
But here you keep us always learning, that we may be always paying you.
Plainly it is a cheat.
What?
Are we always learning, and never able to come to the knowledge of God!
Miserable sinners you found us, and miserable sinners you leave us.`"

[.discourse-part]
__Bishop:__ "`Are you against confession?`"

[.discourse-part]
__John Roberts:__ "`No;
for I believe those who confess and forsake their
sins shall find mercy at the hand of God;
but those who persist in them shall be punished.
But if ever anyone intends to be better, he must throw away his old way,
and get a new one, or turn over a new leaf; for if he keeps on in his old way,
he must always be doing what he ought not to do, and leaving undone what he ought to do;
and he can never do differently.
In this way, I believe in my heart, he mocks God.`"

[.discourse-part]
__Bishop:__ "`How can you say such a thing?`"

[.discourse-part]
__John Roberts:__ "`I will state the case, and you shall judge.
Suppose you had a son, and you daily let him know what you desired him to do,
and even so he day by day, week by week, and year after year, provoked you to your face,
and said, '`Father I have not done what you commanded me to do;
but have done quite the contrary;
and I continue to provoke you to your face in this manner,
once or more every week;`' would you not think him a rebellious child,
and that his petition to you was a mere mockery?
And would it not occasion you to at last disinherit him?`"

[.offset]
After some more discourse, my father told him the time was far spent; and said:

"`If nothing will serve you but my body in prison, here it is in your power,
and if you command me to deliver myself up either to the sheriff,
or to the jailer of Gloucester castle, as your prisoner, I will go,
and will seek no other judge, advocate, or attorney, to plead my cause,
but the great Judge of heaven and earth,
who knows I have nothing but love and good-will in my heart to you and all mankind.`"

[.discourse-part]
__Bishop:__ "`No; you shall go home about your business.`"

[.discourse-part]
__John Roberts:__
"`Then I desire you for the future not to trouble
yourself to send any more bailiffs after me;
for if you desire at any time to let me know by a line or two,
that you wish to speak with me, though it be to send me to prison, if I am well and able,
I will come.`"

[.small-break]
'''

The bishop then called for something to drink; but my father acknowledged his kindness,
and excused himself from drinking.
And the bishop being called out of the room, a man named Cuthbert,
who took offence at my father`'s freedom with the bishop, said, "`Haywood,
you are afraid of nothing; I never met with such a man in my life.
I am afraid of my life, lest such fanatics as you should cut my throat as I sleep.`"

[.discourse-part]
__John Roberts:__ "`I do not wonder that you are afraid.`"

[.discourse-part]
__Cuthbert:__ "`Why should I be afraid any more than you?`"

[.discourse-part]
__John Roberts:__
"`Because I am under the protection of Him who numbers the very hairs of my head,
and without whose providence a sparrow shall not fall to the ground;
but you have Cain`'s mark of envy on your forehead,
and like him are afraid that whoever meets you will kill you.`"

[.discourse-part]
__Cuthbert:__
(In a great rage) "`If all the Quakers in England are not hanged in a month`'s time,
I will be hanged for them!`"

[.discourse-part]
__John Roberts:__ (Smiling,) "`Friend, remember and be as good as your word.`"

[.small-break]
'''

My father and his friend, Amariah Drewett, then took their leave,
and returned home with the answer of peace in their bosoms.

Sometime after this, the bishop and the chancellor in their coaches,
accompanied with Thomas Masters, esq., in his coach,
and about twenty clergymen on horse back,
stopped at my father`'s house on their way to a visitation,
which was to be at Tedbury the next day.
They stopped at the gate, and George Evans, the bishop`'s kinsman,
rode into the yard to call my father.
Coming to the bishop`'s coach-side, the bishop put out his hand,
which my father respectfully took, saying,
"`I could not well go out of the county without seeing you.`"
That is very kind,`" said my father; "`will you please alight and come in,
with those who are along with you?`"

[.discourse-part]
__Bishop:__ "`I thank you John; we are going to Tedbury, and time will not admit of it now;
but I will drink with you, if you please.`"

[.small-break]
'''

My father went in and ordered some drink to be brought,
and then returned to the coach-side.

[.discourse-part]
__George Evans:__ "`John, is your house free to entertain such men as we are?`"

[.discourse-part]
__John Roberts:__ "`Yes, George; I entertain honest men, and sometimes others.`"

[.discourse-part]
__George Evans:__ (To the bishop) "`My lord, John`'s friends are the honest men,
and we are the others.`"

[.discourse-part]
__John Roberts:__ "`That is not fair, George, for you to put your construction on my words;
you should have given me leave to do that.`"

[.small-break]
'''

Squire Thomas Masters came out of his coach, and stood by the bishop`'s coach-side;
and the chancellor, in a sporting way, said to my father,
"`My lord and these gentlemen have been to see your burying-ground,
and we think you keep it very decent.`"
(This piece of ground my father had given to the Friends for that purpose;
it lay at the lower end of his orchard.)

My father answered: "`Yes; though we are against pride,
we think it commendable to be decent.`"

[.discourse-part]
__Chancellor:__ "`But there is one thing among you, which I did not expect to see.
I think it looks a little superstitious;
I mean those grave-stones which are placed at the head and feet of your graves.`"

[.discourse-part]
__John Roberts:__ "`That I confess is what I cannot much plead for;
but it was permitted to gratify some who had their relations there interred, We,
notwithstanding, propose to have them taken up before long,
and converted to some better use.
But I desire you to take notice, that we learned this custom from you,
and I have observed how in many things wherein we have taken you for our pattern,
you have led us wrong; and therefore we are now resolved, with the help of God,
not to follow you one step further.
At this the bishop smiled, and said, "`John I think your beer is long a coming.`"

[.discourse-part]
__John Roberts:__ "`I suppose my wife is willing you should have the best,
and therefore stays to open a fresh vessel.`"

[.discourse-part]
__Bishop:__ "`No, if it be for the best, we will stay.`"

[.small-break]
'''

Presently my mother brought the drink, and when the bishop had drank, he said,
"`I commend you John, you keep a cup of good beer in your house.
I have not drank any that pleased me better since I came from home.
The chancellor drank next; and the cup coming round again to my father`'s hand,
Squire Masters said to him, "`Now, old school-fellow, I hope you will drink to me!`"

[.discourse-part]
__John Roberts:__ "`You know it is not my practice to drink to any man.
If it was, I would as soon drink to you as another,
as being my old acquaintance and school-fellow; but if you are pleased to drink,
you are very welcome.`"

[.small-break]
'''

The Squire then taking the cup into his hand, said, "`Now John,
before my lord and all these gentlemen,
tell me what ceremony or compliment do you Quakers use when you drink to one another.`"

[.discourse-part]
__John Roberts:__ "`None at all.
For me to drink to another, is at best but a form of flattery,
and that borders much on a lie.`"

[.discourse-part]
__Squire Masters:__ "`What do you do then?`"

[.discourse-part]
__John Roberts:__ "`Why, if I have a mind to drink, I take the cup and drink;
and if my friend pleases, he does the same; if not, he may let it alone.`"

[.discourse-part]
__Squire Masters:__ "`Honest John, give me your hand.
Here is to you with all my heart; and according to your own way, if you will drink,
you may, if not, you may let it alone.`"

[.small-break]
'''

My father then offering the cup to the Priest Bull, he refused it,
saying it was "`full of hops and heresy.`"
To which my father replied, "`As for hops, I cannot say much,
not being present at the brewing of it; but as for heresy,
I do assure you neighbour Bull, there is none in my beer; and if you please to drink,
you are welcome; but if not, I desire you to take notice,
that those who are as well able to judge of heresy are present.
Here your lord bishop has drank of it, and commends it; he finds no heresy in the cup.`"

[.discourse-part]
__Bishop:__ (Leaning over the coach-door, and whispering to my father, said) "`John,
I advise you to take care you do not offend against the higher powers.
I have heard great complaints against you,
that you are the ringleader of the Quakers in this country;
and that if you are not suppressed, all will signify nothing.
Therefore, pray John, take care for the future, and do not offend any more.`"

[.discourse-part]
__John Roberts:__ "`I like your counsel very well, and intend to take it.
But you know, God is the higher power; and you mortal men,
however advanced in this world, are but the lower power;
and it is only because I endeavour to be obedient to the will of the higher powers,
that the lower powers are angry with me.
But I hope, with the assistance of God, to take your counsel,
and be subject to the higher powers,
let the lower powers do with me as it may please God to allow them.`"

[.discourse-part]
__Bishop:__ "`I want some more discourse with you.
Will you go with me to Mr. Bull`'s.`"

[.discourse-part]
__John Roberts:__ "`You know he has no goodwill for me.
I had rather attend on you elsewhere.`"

[.discourse-part]
__Bishop:__ "`Will you come tomorrow to Tedbury?`"

[.discourse-part]
__John Roberts:__ "`Yes, if you desire it.`"

[.discourse-part]
__Bishop:__ "`Well I do.`"

[.small-break]
'''

The bishop then took his leave, and went not to the home of the priest George Bull,
at which he was very much offended.

Next morning my father took his son Nathaniel with him, in case the bishop,
in compliance with the violent clamors of the priests, should send him to prison,
which he expected.
As they were passing along a street in Tedbury, they were met by Anthony Sharp,
of Ireland, whose mother lived at Tedbury.
After he understood by my father where he was going,
he asked if he would accept of a companion?
"`If you have a mind to go to prison,`" said my father, "`you may go with me.`"
"`I will venture that,`" replied Anthony, "`for if I do, I shall have good company.`"

When they came to the foot of the stairs which led up to the bishop`'s chamber,
they were spied by George Evans, who said, come up, John, my lord thought you long.
When they came up, the bishop was just setting down to dinner,
with a number of clergymen; and offering to make room for my father, he excused himself,
and retired with his friend till dinner was over.
The bishop spoke to the woman of the house for another room, which, it being market-day,
was soon filled with priests and clothiers, etc.

[.discourse-part]
__Bishop:__ (Putting on a stern countenance) "`Come, John,
I must turn over a new leaf with you.
If you will not promise me to go to church,
and to keep no more of these seditious conventicles^
footnote:[Because of a fear that some meetings were being held
in England in order to plot the overthrow of the government,
all religious gatherings of six persons or more,
besides those sanctioned by the Church of England,
were considered unlawful "`seditious conventicles,`"
and were punishable by fines and imprisonment.]
at your house, I must make a court order, and send you to prison.`"

[.discourse-part]
__John Roberts:__ "`Would you have me shut my doors against my friends?
It was but yesterday that you yourself, and many others here present were at my house;
and I was so far from shutting my doors against you, that I invited you in,
and you should have been welcome to the best entertainment I had.`"

[.discourse-part]
__Bishop:__ "`It is those meetings I speak of which you keep at your house,
to the terror of the country.`"

[.discourse-part]
__John Roberts:__ "`This I will promise you, before all this company,
that if any plotters or ill minded persons come to my house
to plot or conspire against the king or government,
if I know of it, I will be the first informer against them myself,
though I receive not a penny for my labour.
But if honest and sober people come to my house,
to wait upon and worship the God of heaven, in spirit and in truth,
such shall be welcome to me as long as I have a house for them to meet in;
and if I should have none, the Lord will provide one for them.`"

[.discourse-part]
__Bishop:__ "`Will you promise to go to your own parish church to hear divine service?`"

[.discourse-part]
__John Roberts:__ "`I can promise no such thing.
The last time I was there, I was moved and required of the Lord, whom I serve,
to bear testimony against a hireling priest,
who was preaching for hire and divining for money; and he was angry with me,
and caused the people to turn me out.
And I do not intend to trouble him again till he learn more civility,
except the Lord requires it of me.`"

[.discourse-part]
__Bishop:__ "`Send for the constable; I must take another course.`"

[.discourse-part]
__John Roberts:__ "`If you should come to my house under a pretence of friendship,
and in a Judas-like manner, betray me here to send me to prison, then,
as I have hitherto commended you for your moderation,
I should then have occasion to put your name in print,
and cause it to stink before all sober people.
But it is those who set you to this mischief,
and I desire that you no longer hearken to them,
but bid them take up some honest vocation, and rob their honest neighbours no longer.
They are like a company of caterpillars who destroy the fruit of the earth,
and live on the fruit of other men`'s labour.`"

[.small-break]
'''

Then priest Rich, of North-Surry, said, "`Who are those you call caterpillars.`"

[.discourse-part]
__John Roberts:__ "`We herdsman call them caterpillars,
who live on the fruit of other men`'s fields, and on the sweat of other men`'s brows.
And if you do so, you may be one of them.`"

[.discourse-part]
__Priest Rich:__ "`May it please your lordship,
if you permit such a man as this to '`thou`' your lordship,
and call you '`old man,`' what will become of us?^
footnote:[At this time in history,
the correct and plain use of "`thee`" and "`thou`" to a single
person was beginning to give way to "`you`" and "`your.`"
Most modern English speakers are unaware that the words "`you`" and "`your`"
were originally plural pronouns used only to address two or more people,
whereas "`thee`" and "`thou`" were used to address one person.
In the 1600`'s,
it became fashionable (as a means of showing honor or flattery) to use
the plural "`you`" or "`your`" in addressing people of higher social status,
while "`thee`" and "`thou`" were reserved for servants, children,
or people of lower social or economic position.
Early Friends stuck to what was then considered "`plain
language`" (using thee and thou to every single person,
and you and your to two or more),
rather than showing preferment by addressing certain individuals in the plural.
Although it does not appear in the text of this edition
because we have modernized the pronouns,
John Roberts was addressing both the magistrates and priests with "`thee`" and "`thou`",
and for that reason the priest took offense.
Moreover, to address an elderly person as "`old man`" may sound strange to modern ears,
but it was both common and respectful in the 1600`'s.]

[.discourse-part]
__John Roberts:__ "`We honour old age, if it be found in the way of well-doing;
but one would not think you should be such poor students as to forget grammar rules.
You were bred at Oxford and Cambridge!
For what?
I who am a layman, and bred at the plough, understand the singular and plural numbers.
Thee and thou is proper to a single person, even if it be a prince.
You know it is so, old man.
And have you forgot your prayers?
Do you say, '`You O Lord,`' or '`Thou O Lord,`'^
footnote:[Though people of higher social status expected to be addressed by others
with the plural pronouns "`you`" and "`your,`" they nevertheless (hypocritically)
continued to address their Creator with "`thee`" and "`thou.`"]
in your prayers?
Will you not accept the same language from your fellow-mortals,
which you give to the Almighty?
What spirit was that in proud Haman, that sought to make poor Mordecai to bow to him?`"

[.discourse-part]
__Bishop:__ "`This will not do.
Make their court orders.
What is your name?`"

[.discourse-part]
__Anthony Sharp:__ "`My name is Anthony Sharp.`"

[.discourse-part]
__Bishop:__ "`Where do you live?`"

[.discourse-part]
__Anthony Sharp:__ "`At Dublin, in the kingdom of Ireland.`"

[.discourse-part]
__Bishop:__ "`What is your business here?`"

[.discourse-part]
__Anthony Sharp:__ "`My mother lives in this town; and as she is my mother,
and an ancient woman, I thought it my duty to come and see her.`"

[.discourse-part]
__John Roberts:__ "`He only came here in good will to bear me company.
If you please, lay the more on me, and let him go free.`"

[.discourse-part]
__Bishop:__ "`No; he may be as dangerous a person as yourself; and as he came for company,
he shall go with you for company.
Send for the constable to take them into custody.`"

[.small-break]
'''

The woman of the house understanding the constable was to be sent for,
dispatched a messenger to him to bid him get out of the way.
But the messenger missing him, the constable came to the house by accident.
Seeing him, the landlady said, "`What are you doing here,
when honest John Haywood is going to be sent to prison?
Here come along with me.`"
The constable being willing, she concealed him in another room,
and the bishop`'s messenger brought him word that the constable could not be found.
The bishop then said to my father:

[.discourse-part]
__Bishop:__ There are many gentlemen here who have to travel a long way home,
and I can send you to prison in the afternoon;
so you may take your liberty until six o`'clock.

[.small-break]
'''

My father perceived the bishop`'s intent was to get rid of his company,
so he withdrew with his friend Anthony Sharp; and at six o`'clock returned without him,
and found only two persons with the bishop, i.e., Edward Barnet, a surgeon of Cockerton,
and Parson Hall.

[.discourse-part]
__Bishop:__ "`So, John, you are come.
It is well; I want some more discourse with you.`"

[.discourse-part]
__Parson Hall:__ "`And if it please you, my lord, let me discourse with him.`"

[.discourse-part]
__Bishop:__ "`Ay, do, Mr. Hall, John will give you an answer.`"

[.discourse-part]
__Parson Hall:__ "`It is a great pity such a man as you should have the light,
sight and knowledge of the Scriptures;
for the knowledge of the Scriptures has made you mad.`"

[.discourse-part]
__John Roberts:__
"`Why should I not have the privilege of buying the Scriptures
for my money as well as you or any other man?
But you priests, like the Papists, would have us laymen kept in ignorance,
that we might pin our faith on your sleeves; and so the blind lead the blind,
till both fall into the ditch.
But if the knowledge of the Scriptures had made me mad,
the knowledge of the wine pot has almost made you mad;
and if we two mad men should dispute about religion, we should make mad work of it.
But as you are an unworthy man, I will not dispute with you.`"

[.discourse-part]
__Parson Hall:__ "`And if it please you, my lord, he says I am drunk.`"

[.discourse-part]
__John Roberts:__ "`Will you speak an untruth before your lord Bishop.`"

[.discourse-part]
__Parson Hall:__ "`He did say I was drunk, my lord.`"

[.discourse-part]
__Bishop:__ "`What did you say, John?
I will believe you.`"

[.small-break]
'''

My father repeating what he said before, the bishop held up his hands, and smiling, said,
"`Did you say so, John?`"
By this Parson Hall perceived the bishop did not incline to favour him,
and went away in a huff.
The bishop then directing his discourse to my father, said: "`John,
I thought you dealt hardly with me today, in telling me before so many gentlemen,
that I came to your house in a Judas-like manner,
and betrayed you here to send you to prison; for if I had not done what I did,
people would have reported me an encourager of the Quakers.`"

[.discourse-part]
__John Roberts:__ "`If they had, it would have been no discredit to you.`"

[.discourse-part]
__Bishop:__ "`Come now, John, I will burn your court order before your face.
And now, Mr. Barnet, I have a mind to ask John some questions.
John, I have heard Priest Bull say strange things of you;
that you can tell where to find anything that is lost as well as any cunning man;
but I desire to hear from your own mouth.
It was about some cows that a neighbour had lost, and could in no way find them,
till they came to you.`"

[.discourse-part]
__John Roberts:__ "`If you please to hear me, I will tell you the truth of that story.`"

[.discourse-part]
__Bishop:__ "`Please do; I shall believe you, John.`"

[.discourse-part]
__John Roberts:__ "`I had a poor neighbour, who had a wife and six children,
and whom the chief men about us permitted to keep six or seven cows upon the waste land,
which were the principal support of his family,
and preserved them from becoming chargeable to the parish.
One very stormy night the cattle were left in the yard as usual,
but could not be found in the morning.
The man and his sons had sought them to no avail; and after they had been lost four days,
his wife came to me, and in a great deal of grief, cried, '`O Lord!
Master Haywood, we are undone!
My husband and I must go a begging in our old age!
We have lost all our cows!
My husband and the boys have been round the country, and can hear nothing of them.
I will bow down on my bare knees if you will stand now as
our friend!`' I desired she would not be in such agony,
and told her she should not bow down on her knees to me;
but I would gladly help them in what I could.
'`I know,`' said she, '`you are a good man,
and God will hear your prayers.`' '`I desire you,`' said I,
'`to be still and quiet in your mind; perhaps your husband or son may hear of them today;
if not, let your husband get a horse and come to me tomorrow morning as soon as he will,
and I think, if it please God,
to go with him to seek them.`' The woman seemed transported with joy, crying,
'`Then we shall have our cows again!`' Her faith being so strong,
brought the greater exercise upon me, with strong cries unto the Lord,
that He would be pleased to make me instrumental in His hand,
for the help of the poor family.
In the morning early, the old man came and said: '`In the name of God,
which way shall we go and seek them?`' I being deeply concerned in my mind,
did not answer him till he had thrice repeated it; and then I answered,
'`In the name of God we will go to seek them,`' and before I was aware I said,
'`we will go to Malmsbury,
and at the horse-fair we shall find them.`' When I had spoken the
words I was much troubled lest they should not prove true.
It was very early, and the first man we saw,
I asked him if he had seen any stray milk cows thereabouts.
'`What manner of cattle are they?`' said he.
And the old man describing their marks and number,
he told us he saw some of that description standing
and chewing their cuds in their horse-fair;
but thinking they belonged to some of the neighbourhood,
he did not take particular notice of them.
When we came to the place, the old man found them to be his;
but he allowed his transports of joy to rise so high,
that I was ashamed of his behaviour; for he fell a hallowing,
and threw up his mountier cap in the air several times,
till he raised the neighbours out of their beds to see what was the matter.
'`O,`' said he, '`I had lost my cows four or five days ago,
and thought I should never see them again; and this honest neighbour of mine,
told me this morning by his own fireside, nine miles off, that here I should find them,
and here I have them!`' Then up goes his cap again.
I begged of the poor man to be quiet, and take his cows home, and be thankful,
as indeed I was, being reverently bowed in my spirit before the Lord,
in that he was pleased to put the words of truth into my mouth.
And the man drove his cattle home, to the great joy of his family.`"

[.discourse-part]
__Bishop:__ "`I remember another Mr. Bull told me,
about a parcel of sheep a neighbour had lost, and you told him where to find them.`"

[.discourse-part]
__John Roberts:__ "`The truth of the story is this: a neighbour of mine, one John Curtis,
at that time a domestic of George Bull`'s, kept some sheep of his own;
and it so happened that he had lost them for some days; but happening to see me,
and knowing I went often abroad,
he desired me if I should see them anywhere in my travels, to let him know of it.
It happened the next day, I was riding towards my own field, my dogs being with me,
spooked up a hare, and seeing they were likely to kill her, I rode up to take them off,
that she might escape, and by mere accident,
I spied John Curtis`'s sheep in one corner of the field,
in a thick briery part of the hedge,
wherein they stood as secure as if they had been in a pen.
I suppose they had been driven there by the hounds.
When I came home I sent him word of it.
And though this is no more than a common accident,
I find George Bull has endeavoured to improve it to my disadvantage.`"

[.discourse-part]
__Bishop:__ "`I remember one story more he told me about a horse.`"

[.discourse-part]
__John Roberts:__ "`If I shall not tire your patience, I will acquaint you how that was.
One Edward Symons came from London to see his parents at Siddington.
They put his horse to grass with their own, in some ground beyond a part of mine,
called the Fursen Leases, through which they went with the horse;
and when they wanted to take him from the grass they could not find him.
After he had been lost sometime, and they had sought him at several market towns,
somebody, who, it is likely, might have heard the former stories told,
as you might hear them, directed this Edward Symons to me, who telling me the case,
I asked him which way they had led the horse to grass?
He answered through the Fursen Leases.
I said, '`The horse being a stranger in the place,
it is very likely he might endeavour to bend homewards,
and lose himself in the Fursen Leases, for there are a great many acres under that name,
which are so overgrown with furse bushes,
that a horse may lie there concealed a long time.
I therefore advised him to get a good deal of company, and search the places diligently,
as if they were beating for a hare, which, if he did,
I told him I was of the mind he would find him.
The man did take my advice, and found him.
And where is the cunning of all this?
It is no more than their own reason might have directed them to,
had they properly considered the case.`"

[.discourse-part]
__Bishop:__ "`I wanted to hear these stories from your own mouth, though I did not,
nor should I have credited them in the sense Mr. Bull related them.
But I believe you, John.
And now, Mr. Barnet, we will ask John some serious questions.
I can compare him to nothing but a good ring of bells.
You know, Mr. Barnet,
a ring of bells may be made of as good metal as can be put into bells;
but they may be out of tune; so we may say of John;
he is a man of as good metal as I ever met with, but he is quite out of tune.`"

[.discourse-part]
__John Roberts:__ "`You may well say so; for I cannot change my tune after your pipe.`"

[.discourse-part]
__Bishop:__ "`Well, I remember to have read, at the preaching of the apostle,
the heart of Lydia was opened.
Can you tell us what it was that opened the heart of Lydia?`"

[.discourse-part]
__John Roberts:__ "`I believe I can.`"

[.discourse-part]
__Bishop:__ "`I thought so.
I desire you to do it.`"

[.discourse-part]
__John Roberts:__ "`It was nothing but the key of David.`"

[.discourse-part]
__Bishop:__ "`No, now John, I think you are going wrong.`"

[.discourse-part]
__John Roberts:__ "`If you please to speak, I will hear you;
but if you would have me to speak, I desire you to hear me.`"

[.discourse-part]
__Bishop:__ "`Come, Mr. Barnet, we will hear John.`"

[.discourse-part]
__John Roberts:__ "`It is written, '`You have the key of David, which opens,
and none can shut; and if you shut,
none can open.`' And that is no other but the Spirit of our Lord Jesus Christ.
It was the same spiritual key that opened the heart of Moses,
the first penman of the Scripture, and gave him a sight of things from the beginning.
It was the same spiritual key that opened the hearts of all the holy patriarchs,
prophets and apostles, in ages past,
who left their experience of the things of God upon record; which, if they had not done,
you bishops and priests would not have anything to make a trade of;
for it is by telling the experiences of these holy men,
that you get your great bishoprics and parsonages.
And the same spiritual key has, blessed be God,
opened the hearts of thousands in this age, and the same spiritual key has,
in a measure opened my heart, and given me to distinguish between things that differ.
And it must be the same that must open your heart,
if ever you come to have it truly opened.`"

[.discourse-part]
__Bishop:__ "`It is the truth, the very truth.
I never heard it so defined before.
John, I have done you much wrong; I desire you to forgive me;
and I will never wrong you more.`"

[.discourse-part]
__John Roberts:__ "`I do heartily forgive you, as far as it is in my power;
and I truly pray the Father of mercies may forgive you, and make you his.
As to the latter part, that you will never wrong me more; I am of the same mind with you,
for it is in my heart to tell you, I shall never see your face any more.`"

[.discourse-part]
__Bishop:__ "`I have heard you once told the jailer of Gloucester the same,
and it proved true.`"

[.discourse-part]
__John Roberts:__ "`That jailer had been very cruel to me and the rest of our friends,
who were then prisoners.
He had kept us in prison from the sessions to the court,
and then from the court to the sessions, omitting to put our names in the calendar,
that we might have had a hearing.
At length I found means, at the time of the court,
to acquaint the judge by letter of his illegal proceedings.
In consequence of which, we were ordered to be put on the calendar, had a hearing,
and were acquitted.
The judge severely reprimanded the jailer, saying,
'`Sirrah! if ever I hear that you do the like in the future,
I will take care that you shall be jailer here no longer.
I come here to hear and determine causes,
and shall you keep men in prison during your pleasure,
and not put their names in the calendar?`' The jailer coming out of the castle,
was heard by the turnkey to say,
'`It was about Haywood that I was so severely reprimanded by the judge;
and if ever he comes into the castle again,
he shall never come out alive.`' Upon this the turnkey took an opportunity to find me,
and informing me of it, said, '`I would not have you, by any means,
come back to the castle tonight to fetch any of your things; for if you do,
he will certainly detain you for his fees.
I will take care of your things,
as if you yourself were present to do it.`' I acknowledged his kindness, and went home.
When the jailer returned to the castle, he asked the turnkey where the Quakers were?
He answered, he thought it his business to take care of the felons,
and to leave the Quakers to him.
Not long after, being constable, I secured a felon who broke out of the castle,
and sent the turnkey notice of it.
He came over to fetch him back, and begged that, if by any means I could prevent it,
I would not come any more as a prisoner to the castle while his master was jailer;
'`for,`' he said, '`if you do, he swears you shall never go out alive;
and the hour you come in, I will surely leave the castle;
for I cannot stay there to see you abused.`' '`Does he still say so?`' said I '`Yes,
he does,`' said he.
'`Then remember me to him,`' said I, '`and tell him from me,
I shall never see his face any more!`' Soon after
it pleased God to take him away by death;
and in a little time I was brought prisoner there again.`"

[.small-break]
'''

This was the last conference my father had with the bishop, who died soon after.

Sometime after this, our Friends,
having been kept out of their meeting at Cirencester a considerable time,
had continued to meet together in the street.
But orders being given one day to permit them to meet in the house, they did,
and while Theophila Townshend was in prayer, the bishop (successor to bishop Nicholson),
sir John Guise, William Burcher, of Barnsley, justice of the peace,
with a great company attending them, came in.
The bishop laid his hand on Theophila`'s head, saying, "`Enough, good woman, enough;
desist, desist.`"

When she had finished, Richard Bowly, of Cirencester, went to prayer.
And when he had done, sir John Guise asked his name.

[.discourse-part]
__Richard Bowly:__ "`My name is Richard Bowly.`"

[.discourse-part]
__Sir John Guise:__ "`Where do you live?`"

[.discourse-part]
__Richard Bowly:__ "`In this town.`"

[.discourse-part]
__Sir John Guise:__ "`What trade are you?`"

[.discourse-part]
__Richard Bowly:__ "`A maltster.`"

[.discourse-part]
__Sir John Guise:__ "`Write down Richard Bowly twenty pounds for preaching.^
footnote:[During the time of the "`Act Against Seditious
Conventicles,`" both the preacher at an assembly,
and the person who allowed their home to be used as a meeting house,
were subject to a fine of 20 pounds.]
Whose house is this?`"

[.discourse-part]
__John Roberts:__ "`This house has many owners.`"

[.discourse-part]
__Sir John Guise:__
"`But who is the landlord?`"

[.discourse-part]
__John Roberts:__ "`One who is able give us a quiet possession of it.`"

[.discourse-part]
__Sir John Guise:__ "`I demand of you who is the landlord of it.`"

[.discourse-part]
__John Roberts:__ "`The king is our landlord.`"

[.discourse-part]
__Sir John Guise:__
"`How is the king your landlord.`"

[.discourse-part]
__John Roberts:__ "`It is the king`'s land, and we pay the king`'s auditors.
And we are not only his peaceable subjects, but also his good tenants, who pay him rent.
Therefore we have reason to hope he will give us a peaceable possession of our bargain.`"

[.discourse-part]
__Sir John Guise:__
"`Who pays the king`'s auditors?`"

[.discourse-part]
__Richard Bowly:__ "`I do.`"

[.discourse-part]
__Sir John Guise:__ "`Write down Richard Bowly twenty pounds for the house.`"

[.discourse-part]
__John Roberts:__
"`Who is that (speaking to the other justice) who
is so forward to take names and levy fines.`"

[.discourse-part]
__Justice Burcher:__ "`Do not you know him?
It is sir John Guise.`"

[.discourse-part]
__Sir John Guise:__ "`What is that to you?
What is your name?`"

[.discourse-part]
__John Roberts:__ "`I am not ashamed of my name.
But if your name be John Guise, I knew your father by a very remarkable incident;
and I would have you take warning by your father.
A word to the wise is sufficient.`"

[.discourse-part]
__Sir John Guise:__ "`Here constable, take this fellow, and lay him by the heels.^
footnote:[To "`lay someone by the heels`" is an archaic way of saying, lock them up,
put them in shackles, bonds, or into the stocks.]
He affronts me.`"

[.discourse-part]
__John Roberts:__ "`My heels, man?
Fear and dread the living God; I am not afraid of being laid by the heels.`"

[.small-break]
'''

The constable not being quick to obey his orders,
Sir John Guise took my father by the arm, and bid the constable take him by the other.
So they led him into the street, and bid him to go about his business.
"`I am about my business,`" said my father; and on their going in again,
my father followed them.

[.discourse-part]
__Sir John Guise:__ "`Haywood, I thought I had you out.
What are you doing here again?`"

[.discourse-part]
__John Roberts:__ "`I came to see how you behave amongst my friends,
and if you do not behave yourself well, I shall make bold to tell you of it.`"

[.discourse-part]
__Sir John Guise:__ "`I command you in the king`'s name, to go out again.`"

[.discourse-part]
__John Roberts:__ "`If you please to go out first, I will follow.`"

[.small-break]
'''

With some pains he got all the friends out of the house
and ordered all the benches to be brought into the street.
Which being done, my father said, "`The seats are our own,
and we may as well sit as stand.`"
So the friends sat down; but soon after they were broken up and dispersed.

Not long after, John Timbrel, a Friend of Cirencester, wrote to justice Burcher,
and told him (amongst other things) he had previously had a better
opinion of him than to think he would set his hand to such a work;
and that he was sorry that he should join in it.
Sir John Guise being acquainted with this letter by justice Burcher,
sent out a warrant against John Timbrel.
The constable who was to serve the warrant was so civil as to inform him of it,
and to tell him he would not serve it on him until his market was over.
However, he left his market, came to my father, told him of the warrant,
and asked his advice.
My father advised him not to stay for the serving of the warrant,
but to go directly to sir John Guise.
He requested my father to accompany him, so away they went.

When they came before sir John Guise, John Timbrel said,
"`I heard you had sent out a warrant to bring me before you,
but I chose rather to come without it.`"

[.discourse-part]
__Sir John Guise:__ "`What is your name?`"

[.discourse-part]
__John Timbrel:__ "`My name is John Timbrel.`"

[.discourse-part]
__Sir John Guise:__ "`Are you that saucy, pragmatic fellow that wrote to Mr. Burcher,
to deter him from executing the king`'s laws?`"

[.discourse-part]
__John Timbrel:__ "`I did write a letter to William Burcher.`"

[.discourse-part]
__Sir John Guise:__ "`Then you deserve a dungeon.`"

[.discourse-part]
__John Timbrel:__ "`Have you seen the letter?`"

[.discourse-part]
__Sir John Guise:__ "`No, but I have had an account of it.`"

[.discourse-part]
__John Roberts:__ "`Then though you are but a young man,
I desire you to show yourself so much a wise man,
as not to condemn anything you have not seen.
I have seen a copy of it, and think there is a great deal of good advice in it;
and I wish both you and William Burcher were so wise as to take it.`"

[.discourse-part]
__Sir John Guise:__ "`I thought you were the writer or inditer of it,
though Timbrel`'s name was put to it.`"

[.discourse-part]
__John Roberts:__ "`No, I was not.
I knew nothing of it, till after it was sent.`"

[.discourse-part]
__Sir John Guise:__
"`I remember you affronted me the other day before a great number of people,
concerning my father.
Tell me, what do you know of my father?`"

[.discourse-part]
__John Roberts:__ "`Some time ago,
several of my friends being met together with me in a peaceable manner, to worship God,
at Stoke Orchard, your father came in with a file of musketeers at his heels,
and beat and abused us very much.
I then warned him in abundance of love.
Yet he did not seem to regard it, but sent about twelve of us to Gloucester castle.
I then told him God would plead our cause with him.
And I was credibly informed that, not the very night, but the next night after,
he went to bed as well in appearance as usual; but in the morning,
he not ringing a certain bell, which he had by him for that purpose,
at the time he used to do, his housekeeper went up several times,
and thought he was asleep.
But at length, suspecting something more than ordinary, she made a closer inspection;
and perceiving his countenance changed, she threw open the curtains in a great surprise;
on which he just flashed open his eyes, but said not a word.
She asked him how he did; but he made no answer.
Which made her cry out more earnestly; '`Please sir, how do you do?
How is it with you?
For God`'s sake tell me!`' And all he said to her was, '`Oh these Quakers!
Oh these Quakers!
I wish to God I never had a hand against the Quakers!`'
And I did not hear that he ever spoke more.

[.small-break]
'''

Sir John seemed surprised at this relation, and did not contradict it in the least;
which, it is very reasonable to think he would, and with resentment too,
had it not been true.
Yet notwithstanding this fair warning,
he continued his practice of granting warrants against us.
But the officers were generally so civil as to acquaint us with it in time.
Sometime after this, sir John Guise and sir Robert Atkins being at Perrot`'s Brook,
two miles from Cirencester, quarrelled as they were gaming.
Sir John drew his sword, and demanded satisfaction;
but those in the house stepped between and parted them.
They seeming to appear pacified sat down again.
But afterwards, taking a walk together in the bowling-green,
the breast of sir John being filled with resentment, he said, "`Sir Robert,
you gave me a lie; and I will have satisfaction.`"

[.discourse-part]
__Sir Robert Atkins:__
"`If I have said anything more than what is common
for gentlemen to say to each other in their play,
between you and I, I ask your pardon.`"

[.discourse-part]
__Sir John Guise:__ "`If you will go in and ask my pardon before the people of the house,
I will grant it; otherwise I will not.`"

[.discourse-part]
__Sir Robert Atkins:__ "`No, sir John, that is beneath me.`"

[.discourse-part]
__Sir John Guise:__ "`Then draw your sword, or you shall die like a dog.`"

[.small-break]
'''

They both drew, and sir Robert gave him a gentle prick in the arm, and said,
"`I desire you, sir John, to take that for satisfaction.
I could have had you elsewhere; but was unwilling to do you further trouble.`"

[.discourse-part]
__Sir John Guise:__ "`I will kill or be killed.`"

[.discourse-part]
__Sir Robert Atkins:__ "`If that be your mind, look to yourself as well as you can;
for I shall have you at the next pass.

[.small-break]
'''

And so he did; for he ran him through, in at the belly and out at the back;
on which he fell.
Sir Robert stepped up to him, unbuttoned his clothes, tore his shirt down,
and gently drew out his sword; and then after he had well sucked the wound,
taking his handkerchief, he rolled up the corners of it hard,
and thrust it into the orifice; then unbuttoning his clothes, he lifted him up,
and desired him while he was able,
that he would acquaint the people of the house that his death was owing to his own seeking.
And when they were come about him, he was so generous as to say, "`If I die,
sir Robert is clear; for if he had not have killed me, I would have killed him.`"
Sir Robert procured him surgeons; and, after a while, when great pain came upon him,
he lamented himself much, and said,
"`It was the just hand of God upon me for meddling with the Quakers.
But, if he will be pleased to spare me, and try me again,
I will never have a hand against them any more.
For Haywood told me, if I went on persecuting, the same hand that overtook my father,
would overtake me, before I was aware.
He further told me, that I was spurred on by some envious priests;
and also that I would have some time to repent it.
And so I do with all my heart.
And it is true; I could never come into company with Mr. Careless or Mr. Freame,
but they would be stirring me up to put the laws in execution against dissenters^
footnote:[A dissenter was one who separated from the service
and worship of the established church of England.].`"

The sword having missed his entrails, he recovered,
stood candidate for the county afterwards, and never more disturbed our meetings.

[.small-break]
'''

The next thing I shall take notice of, is the proceeding of justice James George,
against my father, my brother Nathaniel and myself.
The justice came to the Ram in Cirencester, and sent for my brother and me.
My father went with us.
And when we came there, he said: "`It is very well John, that you have come too.
I sent for your sons to let them know it is his majesty`'s
pleasure to have the laws put in execution;
and now I take this opportunity to let them and you know,
that we must all be of one church.`"

[.discourse-part]
__John Roberts:__ "`You ought then to be well assured it is the right church.
For if you should be so far permitted to exercise the authority you are entrusted with,
as to force a man against his conscience, to conform to a wrong church,
you cannot rescue that man for having so conformed in the day of account.
I have read indeed,
that our Saviour made a whip of small cords to whip
the buyers and sellers out of the temple;
but I never read that he whipped any in.`"

The window of the room being open, we had a view of Cirencester tower;
and the justice pointing to it, said, "`What do you call that John?`"

[.discourse-part]
__John Roberts:__ "`You may call it a crow-house, if you please.
Do not you see how the crows flock about it?`"

[.discourse-part]
__Justice:__ "`Well, notwithstanding your jesting, I warn you, in the king`'s name,
that you Quakers meet no more, or you will answer it at your peril.`"

[.discourse-part]
__John Roberts:__ "`Then I suppose you think you have done your duty?`"

[.discourse-part]
__Justice:__ "`Yes.`"

[.discourse-part]
__John Roberts:__ "`Then I desire you to give me leave to do my duty.
And I do now warn you, in the name of the King of kings, and Lord of lords,
not to molest or hinder us in the peaceable exercise of our duty to God,
as you will answer for it at another day.`"

[.small-break]
'''

A little time after this, he sent to the officers,
to bid them to go to the Quakers`' meeting house on the next first-day,
and bring their names to him.
The officers were very unwilling to obey his commands;
and some of them acquainted me with their orders,
desiring we would not meet at the usual time,
or otherwise that we would meet at another place.
I told them we did not dare thus to deny the worship of our God: "`For,`" said I,
"`we worship the same God that Daniel did; and he,
notwithstanding the severe decree of the king,
failed not openly to acknowledge God by praying to him, with his window open as usual.
And our God is the same He was in Daniel`'s days,
and just as able to stop the mouths of lions as He was then.
And we are not afraid to trust Him,
having had experience of many deliverances He has wrought for us.`"

The next first-day we met at the time and place we used to meet;
and a good meeting we had,
the living presence of the Lord being sensibly felt amongst us.
One of the constables came in, and delivered a warrant to my brother John,
desiring him to read it.
But my brother put it in his pocket,
telling him he designed to read it when the meeting was over.
"`That will not do,`" said he, "`for if you will not read it now,
I desire you to give it to me again.`"
Which he did.
And then they took a list of several of our names, and carried it to Justice George;
on which he sent out his warrants to seize our goods.
They seized my father`'s corn in his barns, and also locked up the barn doors.

And at that same time, an infectious disease had come upon the justice`'s cattle,
and they were dying off quickly.
His steward told him he must send for John Haywood, or he would lose all his cattle.
"`No,`" said the justice, "`Don`'t send for him now;
because I have warrants out against him and his sons.
Send for anybody else.`"
So the steward sent for another; who did what he could for the cattle,
but to very little avail, for the cattle continued to sicken and die as before.

The steward then told him, "`Please your worship, if you don`'t send for John Haywood,
I believe you will lose all your cattle; for now the bull is sick, and refuses to eat;
and I don`'t find that this other man does them any good.
But if you will please send for John,
I don`'t question but he would be of service to them.`"
"`Send for him then,`" said the justice; "`but don`'t bring him in as you normally do.
When he has done what he can, pay him, and dismiss him.`"
So my father was sent for,
and went--having learned that great Christian lesson
to return good for evil--and did his best for them.

When he had finished, as he was wiping his hands in the entry,
the justice undesignedly came by him; and seeing he could not avoid his notice, said,
"`So, John, you have done something for my cattle, I suppose.`"
"`Yes,`" said my father, "`and I hope it will do them good.`"
"`Well,`" said the justice to the steward, "`pay John.`"

[.discourse-part]
__John Roberts:__ "`No; I will have none of your money.`"

[.discourse-part]
__Justice:__ "`None of my money!
Why so?`"

[.discourse-part]
__John Roberts:__ "`To what purpose is it for me to take a little of your money by retail,
and you will come and take my goods by wholesale.`"

[.discourse-part]
__Justice:__ "`Do not think your coming to drench^
footnote:[i.e. to force medicine down the throat of an animal.]
and bleed my cattle, shall deter me from executing the king`'s laws.`"

[.discourse-part]
__John Roberts:__
"`I seek no favour at your hands.
But when you have done me all the displeasure you are permitted to do,
I will notwithstanding serve you or yours to the utmost of my power.`"

[.discourse-part]
__Justice:__ "`Well, John, you must stay and dine with me.`"

[.discourse-part]
__John Roberts:__ "`Perhaps I shall intrude if I stay, I had rather be excused.`"

[.discourse-part]
__Justice:__ "`It is no intrusion, John; you shall stay.`"

[.small-break]
'''

So my father stayed,
and presented him with a short work of Thomas Ellwood`'s against persecution; which,
together with my father`'s readiness to serve him, so wrought upon him,
that I do not remember any of his corn was taken from him at that time.
But my brother Nathaniel and myself, being partners in trade in Cirencester,
were fined by this Justice George, for ourselves,
and the persons present with us at the meeting, seventy pounds.

Sometime after this, Sir Thomas Cutter came to our house, with other justices,
the sheriff of the county, his servants, and two constables.
Our neighbours, in good will to us, shut our doors,
and the maid fastened them on the inside.
But the justices gave orders they should be broken open.
A young woman being in the shop when this was done, ran out at the back door in a fright.
Sir Thomas seeing this, said, "`There is one gone!
There might as well be five hundred gone;
I will take my oath that there was a conventicle here.`"
I being near him, bid him take care what he said or swore, because he must give account,
and he knew not how soon.
A servant belonging to one of them took off my hat, and laid it on the table.
I took it and put it on again, saying,
"`I hope a man may keep his hat on in his own house, without offence to any man.`"

[.discourse-part]
__Sir Thomas:__ "`What is your name?`"

[.discourse-part]
__Daniel Roberts:__ "`Daniel Roberts.`"

[.discourse-part]
__Sir Thomas:__ "`Can you swear?`"

[.discourse-part]
__Daniel Roberts:__ "`Not that I know of; I never tried.`"

[.discourse-part]
__Sir Thomas:__ "`Then you must begin now.`"

[.discourse-part]
__Daniel Roberts:__ "`I think I shall not.`"

[.discourse-part]
__Sir Thomas:__ "`How will you help it?`"

[.discourse-part]
__Daniel Roberts:__ "`By not doing it.
But if you can convince me by that book in your hand
(which was a bible) that it is lawful to swear,
since Christ forbids it, then I will swear.
For when men come and say you must swear or suffer,
it is but reasonable to expect such men should be qualified to prove it lawful.
Our Saviour says, '`Swear not at all;`' You say '`I must swear.`' Tell me,
which must I obey?

[.discourse-part]
__Sir Thomas:__ "`Well, Daniel, if you will not swear, you must go to jail.`"

[.discourse-part]
__Daniel Roberts:__ "`The will of God be done.
For be it known unto you, we had rather be in prison, and enjoy our peace with God,
than be at liberty, and break our peace with Him.`"

[.discourse-part]
__Justice Parsons:__ "`I suppose you are one of John Haywood`'s sons?`"

[.discourse-part]
__Daniel Roberts:__ "`Yes.`"

[.discourse-part]
__Justice Parsons:__ "`I am sorry for that.`"

[.discourse-part]
__Daniel Roberts:__ "`Why are you sorry for that?
I never heard an honest man speak against my father in all my life.
What have you against him?`"

[.discourse-part]
__Sir Thomas:__ "`That he is not only misled himself,
but he is also a means to mislead others.`"

[.discourse-part]
__Daniel Roberts:__ "`If you have nothing against him but his obedience to the law of God,
that is no more than the accusers of honest Daniel had against him;
and that does not concern me.`"

[.discourse-part]
__Sir Thomas:__ "`His worshipping God in the way he does is crime enough.`"

[.discourse-part]
__Daniel Roberts:__ "`Then I hope I shall be a criminal as long as I live.`"

[.small-break]
'''

They then seized what goods they pleased, and took them away with them.
And after they had tendered us oaths twice more, our court order was made,
and we were sent to Gloucester castle,
where we found several of our Friends who had arrived before us;
and together with those that were sent in soon after us,
we became a family of forty or fifty.
The jailer`'s name was John Landborne;
and for a piece of service I did him gratis in his absence (i.e. officiating as key-turner,
and preventing two notorious robbers from breaking out)
I was able to prevail with him to let several of our friends
go home for a time when occasion particularly required it.

We, being a large number of us in prison,
had often large meetings on the first-days in the castle.
Several of the prisoners who were not of our number,
as well as several people out of the city, would come and sit down with us.
Therefore Richard Parsons, one of our persecutors, who lived in the city,
came to our morning meeting, accompanied with several others.
My father was present with us, and Henry Panton, who had formerly been a fencing master,
was preaching when they came in,
concerning the confession of some who perpetually say they do what they ought not,
and leave undone what they ought to do.
Richard Parsons, who was a priest, a chancellor, and a justice, took hold of these words,
and told him he was complaining of others for what he was doing himself;
"`For,`" said he, "`you are now doing what you ought not,
and leaving undone what you ought to do.`"
Then, catching hold of Henry`'s grey locks, he sought to pull him down.
But Henry being a tall man, strong and active, though advanced in years,
he stood his ground, and spoke over Richard Parsons`' head.
Parsons then strove to stop his mouth, but he avoided it,
by turning his head to one side.

When Henry had finished speaking, a Friend stood up, and said,
"`It is a sign that the devil is hard put to have his drudgery done,
when priests must leave their pulpits and parishioners to take
up the business of informers against poor prisoners in the prison.`"
After Priest Parsons had been sometime endeavouring to get the names of some present,
and nobody would give him information, he thus broke out: "`If you are here,
I shall get even with you another way.`"
For he had somehow acquired a list of several prisoners`' names;
and taking for granted that these names were all present at the time,
he sent out his warrants for seizing their goods.
However, herein he was mistaken; for several were then absent who were on his list;
among whom was Lettice Gush, a widow, who lived about twenty miles distant.
Some officers being sent to her house to seize her goods for being present at this meeting,
when she was actually twenty miles from the place; when the officers came,
she told them she was not at the meeting; and to convince them,
she persuaded them to go with her to her landlord, who was also a justice of the peace,
and knew what she said to be true.
When they came before him, and showed him the warrant, he said, "`What a rascal!
Is this Priest Parsons!
Here he says,
he will take his oath that my tenant was convicted
by him of being at a conventicle in Gloucester castle,
such a day of the month; and I will take my oath that she was at home at the same time,
which is twenty miles off!
If you touch any of her goods by virtue of this warrant, it will be at your peril.
I will assure you if you do, I will stick close to your skirts.`"

[.discourse-part]
__Officer:__ "`What can be done in this case?
How can we make a legal return of the warrant without executing it?`"

[.discourse-part]
__Landlord:__ "`Carry it back to Mr. Parsons, and I will bear you out in it.`"

[.small-break]
'''

So they returned, without giving her any further trouble.
Another warrant was issued out against Francis Boy, a physician, on the same account,
and of the same value, who was likewise absent at the time of his supposed conviction.
When the officers came to seize his goods, he was not at home.
So his cattle were taken away to the value of between twenty and thirty pounds.
He afterwards, on inspection, found by his books,
that he was attending a gentleman at the time he was said to be convicted.
To this gentleman he went,
and inquired of him if he could remember the day he attended him?
The gentleman answered, "`He had good reason to remember it; for,`" said he,
"`if you had not done what you did for me that day,
I believe I should have been now in my grave.`"
He then informed the gentleman of the reason that induced him to give him that trouble.
"`Well,`" replied he, "`I advise you to appeal to the next quarter-sessions for redress;
and you may assure yourself I will endeavour to serve you in whatever lays in my power;
for I will take my oath before any judge or bench of justices in England,
that you were with me that day.`"
But it so fell out that he had no occasion to appeal.
For it soon was well known that he had such substantial evidence in his favour;
and his cattle were returned before the sessions.

Not long after it pleased God to visit my dear father with a sickness that proved mortal.
I had leave to attend him the major part of the time he was sick;
and the Lord was pleased to favour him with his living presence in his last moments;
and having honourably finished his days`' work, he departed this life in the year 1683,
and was interred in the piece of ground he had long before given to Friends for a burying-place,
situated at the lower end of his orchard, at Siddington, near Cirencester.

Some days after his interment, I had news that my brother and myself,
with four Friends more, were discharged by the judge;
but that the another four were detained for the fees.
I therefore went down to use my interest for their discharge.
I found the judge ill in bed;
and he told me he was very willing to remit the fees belonging to himself;
but there were some fees due to the under-sheriff, and those were not in his power.
But soon after providence so ordered that we all had our liberty;
and I came and settled at my present habitation at Chesham, in Buckinghamshire,
where I have now dwelt about forty years.

Thus, considering that it would be a great pity if those remarkable providences
of the Almighty should not be recorded for the benefit of posterity,
I was willing for my own perusal and that of my family, and some few particular friends,
to commit them to writing.
In the doing which,
respecting the several conferences my father had with the bishops and others,
before mentioned,
I have been careful to pen them down in the same words they were then expressed in,
as near as I could recollect,
or at least to retain the genuine sense and purport of them.
Which, reader,
if they tend to your confirmation and encouragement in a course of true Christian piety,
I have my end; who am your sincere friend,

[.signed-section-signature]
Daniel Roberts.

[.signed-section-context-close]
Chesham, Fourth mo., 1725.
